-- ============================================
-- DW2_NAV SCHEMA - NAV Data Warehouse Tables
-- ============================================
-- 14 READ-ONLY external tables
-- Source: Microsoft Dynamics NAV Data Warehouse (DW2.nav)
-- Generated from Prisma schema

CREATE SCHEMA IF NOT EXISTS dw2_nav;

-- =============================================================================
-- Table 1: pallet_bin_content
-- =============================================================================
CREATE TABLE dw2_nav.pallet_bin_content (
    source_db TEXT NOT NULL,
    hash TEXT,
    bin TEXT NOT NULL,
    location TEXT NOT NULL,
    pallet_no_ TEXT NOT NULL,
    box_no_ TEXT NOT NULL,
    item_no_ TEXT NOT NULL,
    variant_no_ TEXT NOT NULL,
    lot_no_ TEXT NOT NULL,
    serial_no_ TEXT NOT NULL,
    unit_of_measure TEXT NOT NULL,
    description TEXT,
    quantity_base DECIMAL,
    quantity DECIMAL,
    qty_per_uom DECIMAL,
    expiry_date TIMESTAMP,
    warranty_date TIMESTAMP,
    last_handled_date TIMESTAMP,
    last_handled_time TIMESTAMP,
    creation_date TIMESTAMP,
    creation_time TIMESTAMP,
    qa_status TEXT,
    source_type INTEGER,
    source_sub_type INTEGER,
    source_id TEXT,
    source_reference_no_ INTEGER,
    pallet_height DECIMAL,
    counted BOOLEAN,
    PRIMARY KEY (source_db, bin, location, pallet_no_, box_no_, item_no_, variant_no_, lot_no_, serial_no_, unit_of_measure)
);

-- =============================================================================
-- Table 2: item
-- =============================================================================
CREATE TABLE dw2_nav.item (
    validfrom TIMESTAMP,
    validto TIMESTAMP,
    source_db TEXT NOT NULL,
    hash TEXT,
    no_ TEXT NOT NULL,
    no_2 TEXT,
    description TEXT,
    description_2 TEXT,
    base_unit_of_measure TEXT,
    price_unit_conversion INTEGER,
    type INTEGER,
    inventory_posting_group TEXT,
    item_disc_group TEXT,
    allow_invoice_disc BOOLEAN,
    unit_price DECIMAL,
    price_profit_calculation INTEGER,
    profit DECIMAL,
    costing_method INTEGER,
    unit_cost DECIMAL,
    last_direct_cost DECIMAL,
    cost_is_adjusted BOOLEAN,
    allow_online_adjustment BOOLEAN,
    vendor_no_ TEXT,
    vendor_item_no_ TEXT,
    lead_time_calculation VARCHAR(32),
    reorder_point DECIMAL,
    maximum_inventory DECIMAL,
    reorder_quantity DECIMAL,
    alternative_item_no_ TEXT,
    unit_list_price DECIMAL,
    gross_weight DECIMAL,
    net_weight DECIMAL,
    units_per_parcel DECIMAL,
    unit_volume DECIMAL,
    country_region_purchased_code TEXT,
    blocked BOOLEAN,
    block_reason TEXT,
    gen_prod_posting_group TEXT,
    country_region_of_origin_code TEXT,
    reserve INTEGER,
    global_dimension_1_code TEXT,
    global_dimension_2_code TEXT,
    lot_size DECIMAL,
    last_unit_cost_calc_date TIMESTAMP,
    minimum_order_quantity DECIMAL,
    safety_stock_quantity DECIMAL,
    order_multiple DECIMAL,
    safety_lead_time VARCHAR(32),
    sales_unit_of_measure TEXT,
    purch_unit_of_measure TEXT,
    reordering_policy INTEGER,
    include_inventory BOOLEAN,
    manufacturer_code TEXT,
    item_category_code TEXT,
    product_group_code TEXT,
    phys_invt_counting_period_code TEXT,
    last_counting_period_update TIMESTAMP,
    use_cross_docking BOOLEAN,
    next_counting_start_date TIMESTAMP,
    next_counting_end_date TIMESTAMP,
    expiration_date_type INTEGER,
    expiration_date_rule INTEGER,
    buyer_code TEXT,
    crv DECIMAL,
    shelf_life_in_days INTEGER,
    shelf_life TEXT,
    specials_list INTEGER,
    sodexo_only INTEGER,
    pack_size TEXT,
    item_class TEXT,
    active_since TIMESTAMP,
    current_vendor_no_ TEXT,
    commodity_dependency INTEGER,
    commodity_fee_basis INTEGER,
    fair_market_value DECIMAL,
    cmdy_value_exception INTEGER,
    df_lb_per_case DECIMAL,
    commodity_additional_allowance DECIMAL,
    onelink_order_guide INTEGER,
    market_price_item BOOLEAN,
    zero_price_allowed BOOLEAN,
    zone TEXT,
    repack_item_no_ TEXT,
    repack_qty DECIMAL,
    lb_item_no_ TEXT,
    master_item_no_ TEXT,
    master_item BOOLEAN,
    njpa BOOLEAN,
    always_create_pick BOOLEAN,
    status TEXT,
    rebate_vendor_no_ TEXT,
    catch_weight BOOLEAN,
    use_unit_of_measure_dimensions BOOLEAN,
    producer_of_good_indicator INTEGER,
    item_upc_ean_number TEXT,
    routing_no_ TEXT,
    production_bom_no_ TEXT,
    order_tracking_policy INTEGER,
    critical BOOLEAN,
    suggested_weeks_on_hand DECIMAL,
    city_state_zip_code_of_origin TEXT,
    category_class_code TEXT,
    gtin TEXT,
    mfg_name TEXT,
    non_domestic BOOLEAN,
    food_item BOOLEAN,
    last_direct_lb_cost DECIMAL,
    exception_type TEXT,
    PRIMARY KEY (source_db, no_)
);

-- =============================================================================
-- Table 3: customer
-- =============================================================================
CREATE TABLE dw2_nav.customer (
    source_db TEXT NOT NULL,
    hash TEXT,
    no_ TEXT NOT NULL,
    name TEXT,
    name_2 TEXT,
    address TEXT,
    address_2 TEXT,
    city TEXT,
    contact TEXT,
    phone_no_ TEXT,
    global_dimension_1_code TEXT,
    global_dimension_2_code TEXT,
    customer_posting_group TEXT,
    payment_terms_code TEXT,
    salesperson_code TEXT,
    shipment_method_code TEXT,
    invoice_disc_code TEXT,
    customer_disc_group TEXT,
    country_region_code TEXT,
    print_statements BOOLEAN,
    bill_to_customer_no_ TEXT,
    payment_method_code TEXT,
    location_code TEXT,
    combine_shipments BOOLEAN,
    gen_bus_posting_group TEXT,
    post_code TEXT,
    county TEXT,
    e_mail TEXT,
    tax_area_code TEXT,
    tax_liable BOOLEAN,
    reserve INTEGER,
    primary_contact_no_ TEXT,
    allow_line_disc BOOLEAN,
    tax_area_id TEXT,
    csr TEXT,
    district_group_code TEXT,
    price_orders_at_shipment BOOLEAN,
    geographic_code TEXT,
    sodexo_unit_no_ TEXT,
    ra_no_ TEXT,
    hours_of_operation TEXT,
    bill_to_primary_contact_no_ TEXT,
    default_external_document_no_ TEXT,
    dod_usda_customer_no_ TEXT,
    allow_zero_qty_lines BOOLEAN,
    combine_bread_broadline BOOLEAN,
    online_customer BOOLEAN,
    pricing_uses_order_date INTEGER,
    charge_storage_fees INTEGER,
    rebate_invoices BOOLEAN,
    ups_location_code TEXT,
    exclude_from_crv BOOLEAN,
    use_invoice_with_zones BOOLEAN,
    special_instructions TEXT,
    bill_to_customer INTEGER,
    customer_accepts_subs INTEGER,
    keys_to_gate INTEGER,
    keys_to_kitchen INTEGER,
    keys_to_walk_in INTEGER,
    co_op_code TEXT,
    "5_star_exception" INTEGER,
    do_not_combine BOOLEAN,
    do_not_break_item INTEGER,
    tls INTEGER,
    order_type TEXT,
    njpa_code INTEGER,
    customer_drop_type TEXT,
    pallet_per_item INTEGER,
    audit_picks BOOLEAN,
    edi_invoice INTEGER,
    edi_trade_partner TEXT,
    dod_customer BOOLEAN,
    chain_name TEXT,
    priority INTEGER,
    legacy_no_ TEXT,
    sync_filter TEXT,
    credit_limit_lcy DECIMAL,
    type TEXT,
    "group" TEXT,
    status TEXT,
    account_type TEXT,
    commodity_region TEXT,
    PRIMARY KEY (source_db, no_)
);

-- =============================================================================
-- Table 4: item_ledger_entry
-- =============================================================================
CREATE TABLE dw2_nav.item_ledger_entry (
    source_db TEXT NOT NULL,
    hash TEXT,
    entry_no_ INTEGER NOT NULL,
    item_no_ TEXT,
    posting_date TIMESTAMP,
    entry_type INTEGER,
    source_no_ TEXT,
    document_no_ TEXT,
    description TEXT,
    location_code TEXT,
    quantity DECIMAL,
    remaining_quantity DECIMAL,
    invoiced_quantity DECIMAL,
    applies_to_entry INTEGER,
    open BOOLEAN,
    global_dimension_1_code TEXT,
    global_dimension_2_code TEXT,
    positive BOOLEAN,
    source_type INTEGER,
    drop_shipment BOOLEAN,
    country_region_code TEXT,
    document_date TIMESTAMP,
    external_document_no_ TEXT,
    no_series TEXT,
    document_type INTEGER,
    document_line_no_ INTEGER,
    order_type INTEGER,
    order_no_ TEXT,
    order_line_no_ INTEGER,
    dimension_set_id INTEGER,
    assemble_to_order BOOLEAN,
    variant_code TEXT,
    qty_per_unit_of_measure DECIMAL,
    unit_of_measure_code TEXT,
    item_category_code TEXT,
    product_group_code TEXT,
    completely_invoiced BOOLEAN,
    last_invoice_date TIMESTAMP,
    correction BOOLEAN,
    shipped_qty_not_returned DECIMAL,
    lot_no_ TEXT,
    expiration_date TIMESTAMP,
    item_tracking INTEGER,
    return_reason_code TEXT,
    bill_to_customer_no_ TEXT,
    reason_code TEXT,
    true_posting_date_time TIMESTAMP,
    PRIMARY KEY (source_db, entry_no_)
);

-- =============================================================================
-- Table 5: purch_rcpt_header
-- =============================================================================
CREATE TABLE dw2_nav.purch_rcpt_header (
    source_db TEXT NOT NULL,
    hash TEXT,
    no_ TEXT NOT NULL,
    buy_from_vendor_no_ TEXT,
    pay_to_vendor_no_ TEXT,
    pay_to_name TEXT,
    pay_to_name_2 TEXT,
    pay_to_address TEXT,
    pay_to_address_2 TEXT,
    pay_to_city TEXT,
    pay_to_contact TEXT,
    your_reference TEXT,
    ship_to_code TEXT,
    ship_to_name TEXT,
    ship_to_name_2 TEXT,
    ship_to_address TEXT,
    ship_to_address_2 TEXT,
    ship_to_city TEXT,
    ship_to_contact TEXT,
    order_date TIMESTAMP,
    posting_date TIMESTAMP,
    expected_receipt_date TIMESTAMP,
    posting_description TEXT,
    payment_terms_code TEXT,
    due_date TIMESTAMP,
    payment_discount DECIMAL,
    pmt_discount_date TIMESTAMP,
    shipment_method_code TEXT,
    location_code TEXT,
    shortcut_dimension_1_code TEXT,
    shortcut_dimension_2_code TEXT,
    vendor_posting_group TEXT,
    invoice_disc_code TEXT,
    purchaser_code TEXT,
    order_no_ TEXT,
    vendor_order_no_ TEXT,
    vendor_shipment_no_ TEXT,
    sell_to_customer_no_ TEXT,
    reason_code TEXT,
    gen_bus_posting_group TEXT,
    vat_country_region_code TEXT,
    buy_from_vendor_name TEXT,
    buy_from_vendor_name_2 TEXT,
    buy_from_address TEXT,
    buy_from_address_2 TEXT,
    buy_from_city TEXT,
    buy_from_contact TEXT,
    pay_to_post_code TEXT,
    pay_to_county TEXT,
    pay_to_country_region_code TEXT,
    buy_from_post_code TEXT,
    buy_from_county TEXT,
    buy_from_country_region_code TEXT,
    ship_to_post_code TEXT,
    ship_to_county TEXT,
    ship_to_country_region_code TEXT,
    correction BOOLEAN,
    document_date TIMESTAMP,
    payment_method_code TEXT,
    no_series TEXT,
    order_no_series TEXT,
    user_id TEXT,
    source_code TEXT,
    dimension_set_id INTEGER,
    buy_from_contact_no_ TEXT,
    pay_to_contact_no_ TEXT,
    lead_time_calculation VARCHAR(32),
    disposition_no_ TEXT,
    offering_no_ TEXT,
    co_op_code TEXT,
    freight_vendor TEXT,
    freight_amount DECIMAL,
    PRIMARY KEY (source_db, no_)
);

-- =============================================================================
-- Table 6: purchase_header
-- =============================================================================
CREATE TABLE dw2_nav.purchase_header (
    source_db TEXT NOT NULL,
    hash TEXT,
    document_type INTEGER NOT NULL,
    no_ TEXT NOT NULL,
    buy_from_vendor_no_ TEXT,
    pay_to_vendor_no_ TEXT,
    pay_to_name TEXT,
    pay_to_address TEXT,
    pay_to_address_2 TEXT,
    pay_to_city TEXT,
    pay_to_contact TEXT,
    your_reference TEXT,
    ship_to_name TEXT,
    ship_to_address TEXT,
    ship_to_address_2 TEXT,
    ship_to_city TEXT,
    ship_to_contact TEXT,
    order_date TIMESTAMP,
    posting_date TIMESTAMP,
    expected_receipt_date TIMESTAMP,
    posting_description TEXT,
    payment_terms_code TEXT,
    due_date TIMESTAMP,
    payment_discount DECIMAL,
    pmt_discount_date TIMESTAMP,
    shipment_method_code TEXT,
    location_code TEXT,
    shortcut_dimension_1_code TEXT,
    shortcut_dimension_2_code TEXT,
    vendor_posting_group TEXT,
    invoice_disc_code TEXT,
    language_code TEXT,
    purchaser_code TEXT,
    order_class TEXT,
    no_printed INTEGER,
    on_hold TEXT,
    applies_to_doc_type INTEGER,
    applies_to_doc_no_ TEXT,
    bal_account_no_ TEXT,
    receive BOOLEAN,
    invoice BOOLEAN,
    print_posted_documents BOOLEAN,
    receiving_no_ TEXT,
    posting_no_ TEXT,
    last_receiving_no_ TEXT,
    last_posting_no_ TEXT,
    vendor_order_no_ TEXT,
    vendor_shipment_no_ TEXT,
    vendor_invoice_no_ TEXT,
    vendor_cr_memo_no_ TEXT,
    vat_registration_no_ TEXT,
    sell_to_customer_no_ TEXT,
    gen_bus_posting_group TEXT,
    vat_country_region_code TEXT,
    buy_from_vendor_name TEXT,
    buy_from_address TEXT,
    buy_from_address_2 TEXT,
    buy_from_city TEXT,
    buy_from_contact TEXT,
    pay_to_post_code TEXT,
    pay_to_county TEXT,
    pay_to_country_region_code TEXT,
    buy_from_post_code TEXT,
    buy_from_county TEXT,
    buy_from_country_region_code TEXT,
    ship_to_post_code TEXT,
    ship_to_county TEXT,
    ship_to_country_region_code TEXT,
    order_address_code TEXT,
    document_date TIMESTAMP,
    payment_method_code TEXT,
    no_series TEXT,
    posting_no_series TEXT,
    receiving_no_series TEXT,
    status INTEGER,
    invoice_discount_calculation INTEGER,
    invoice_discount_value DECIMAL,
    prepayment_no_ TEXT,
    last_prepayment_no_ TEXT,
    prepmt_cr_memo_no_ TEXT,
    last_prepmt_cr_memo_no_ TEXT,
    prepayment DECIMAL,
    prepayment_no_series TEXT,
    compress_prepayment BOOLEAN,
    prepayment_due_date TIMESTAMP,
    prepmt_cr_memo_no_series TEXT,
    prepmt_posting_description TEXT,
    prepmt_pmt_discount_date TIMESTAMP,
    prepmt_payment_terms_code TEXT,
    prepmt_payment_discount DECIMAL,
    incoming_document_entry_no_ INTEGER,
    dimension_set_id INTEGER,
    doc_no_occurrence INTEGER,
    buy_from_contact_no_ TEXT,
    pay_to_contact_no_ TEXT,
    requested_receipt_date TIMESTAMP,
    promised_receipt_date TIMESTAMP,
    lead_time_calculation VARCHAR(32),
    vendor_authorization_no_ TEXT,
    return_shipment_no_series TEXT,
    ship BOOLEAN,
    last_return_shipment_no_ TEXT,
    id TEXT,
    assigned_user_id TEXT,
    irs_1099_code TEXT,
    rebate_start_date TIMESTAMP,
    rebate_end_date TIMESTAMP,
    disposition_no_ TEXT,
    offering_no_ TEXT,
    rebate_doc_handling INTEGER,
    pricing_confirm TEXT,
    labels_printed BOOLEAN,
    order_closed BOOLEAN,
    co_op_code TEXT,
    include_qty_for_pick BOOLEAN,
    available_date TIMESTAMP,
    manual_available_date INTEGER,
    priority INTEGER,
    drop_ship_so_no_ TEXT,
    zone TEXT,
    geographic_code TEXT,
    allow_order_below_minimum BOOLEAN,
    edi_order BOOLEAN,
    edi_internal_doc_no_ TEXT,
    edi_po_generated BOOLEAN,
    edi_po_gen_date TIMESTAMP,
    edi_released BOOLEAN,
    edi_ship_adv_gen BOOLEAN,
    edi_ship_adv_gen_date TIMESTAMP,
    edi_update_int_doc_no_ TEXT,
    edi_trade_partner TEXT,
    edi_buy_from_code TEXT,
    e_ship_agent_code TEXT,
    e_ship_agent_service TEXT,
    world_wide_service BOOLEAN,
    residential_delivery BOOLEAN,
    cod_payment BOOLEAN,
    cod_cashiers_check INTEGER,
    shipping_payment_type INTEGER,
    third_party_ship_account_no_ TEXT,
    shipping_insurance INTEGER,
    e_mail_confirmation_handled INTEGER,
    show_order BOOLEAN,
    freight_vendor TEXT,
    freight_amount DECIMAL,
    usda_quote_no_ TEXT,
    usda_po_no_ TEXT,
    PRIMARY KEY (source_db, document_type, no_)
);

-- =============================================================================
-- Table 7: transfer_header
-- =============================================================================
CREATE TABLE dw2_nav.transfer_header (
    source_db TEXT NOT NULL,
    hash TEXT,
    no_ TEXT NOT NULL,
    transfer_from_code TEXT,
    transfer_to_code TEXT,
    posting_date TIMESTAMP,
    shipment_date TIMESTAMP,
    receipt_date TIMESTAMP,
    PRIMARY KEY (source_db, no_)
);

-- =============================================================================
-- Table 8: sales_price
-- =============================================================================
CREATE TABLE dw2_nav.sales_price (
    source_db TEXT NOT NULL,
    hash TEXT,
    item_no_ TEXT NOT NULL,
    sales_type INTEGER NOT NULL,
    sales_code TEXT NOT NULL,
    starting_date TIMESTAMP NOT NULL,
    currency_code TEXT NOT NULL,
    variant_code TEXT NOT NULL,
    unit_of_measure_code TEXT NOT NULL,
    minimum_quantity DECIMAL NOT NULL,
    unit_price DECIMAL,
    price_includes_vat BOOLEAN,
    allow_invoice_disc_ BOOLEAN,
    ending_date TIMESTAMP,
    allow_line_disc_ BOOLEAN,
    fob_cost DECIMAL,
    delivered_cost DECIMAL,
    rebate_amount DECIMAL,
    fee_for_service DECIMAL,
    customer_bid_no_ TEXT,
    comment TEXT,
    mfg_bid_no_ TEXT,
    mfg_item_no_ TEXT,
    customer_bid_qty_ DECIMAL,
    contract_expiration_date TIMESTAMP,
    item_pack_size TEXT,
    bid_line_no_ TEXT,
    price_id INTEGER,
    price_type INTEGER,
    pricing_method INTEGER,
    njpa_cost DECIMAL,
    njpa_super_cost DECIMAL,
    contract_spec INTEGER,
    price_per_pound DECIMAL,
    PRIMARY KEY (source_db, item_no_, sales_type, sales_code, starting_date, currency_code, variant_code, unit_of_measure_code, minimum_quantity)
);

-- =============================================================================
-- Table 9: short_ship
-- =============================================================================
CREATE TABLE dw2_nav.short_ship (
    source_db TEXT NOT NULL,
    hash TEXT,
    invoice_no_ TEXT NOT NULL,
    item_no_ TEXT NOT NULL,
    line_no_ INTEGER NOT NULL,
    bill_to_customer_no_ TEXT,
    bill_to_name TEXT,
    sell_to_customer_no_ TEXT,
    sell_to_name TEXT,
    invoice_date TIMESTAMP,
    csr TEXT,
    order_quantity DECIMAL,
    shipped_quantity DECIMAL,
    short_ship_quantity DECIMAL,
    short_ship_reason_code TEXT,
    reviewed INTEGER,
    reviewed_by TEXT,
    external_document_no_ TEXT,
    reviewed_date TIMESTAMP,
    location_code TEXT,
    route_no_ TEXT,
    stop_no_ TEXT,
    shipment_date TIMESTAMP,
    buyer_code TEXT,
    suggested_sub TEXT,
    bin_code TEXT,
    cross_reference_no_ TEXT,
    substitution_reason_code TEXT,
    datetime_printed TIMESTAMP,
    PRIMARY KEY (source_db, invoice_no_, item_no_, line_no_)
);

-- =============================================================================
-- Table 10: stockkeeping_unit
-- =============================================================================
CREATE TABLE dw2_nav.stockkeeping_unit (
    source_db TEXT NOT NULL,
    hash TEXT,
    location_code TEXT NOT NULL,
    item_no_ TEXT NOT NULL,
    variant_code TEXT NOT NULL,
    shelf_no_ TEXT,
    unit_cost DECIMAL,
    standard_cost DECIMAL,
    last_direct_cost DECIMAL,
    vendor_no_ TEXT,
    vendor_item_no_ TEXT,
    lead_time_calculation VARCHAR(32),
    reorder_point DECIMAL,
    maximum_inventory DECIMAL,
    reorder_quantity DECIMAL,
    minimum_order_quantity DECIMAL,
    maximum_order_quantity DECIMAL,
    safety_stock_quantity DECIMAL,
    order_multiple DECIMAL,
    safety_lead_time VARCHAR(32),
    reordering_policy INTEGER,
    include_inventory BOOLEAN,
    use_cross_docking BOOLEAN,
    blocked INTEGER,
    specials_list INTEGER,
    special_order INTEGER,
    velocity TEXT,
    status TEXT,
    pallet_ti INTEGER,
    pallet_hi INTEGER,
    always_putaway_to_pick INTEGER,
    new_velocity TEXT,
    pick_zone_code TEXT,
    customer_lead_time INTEGER,
    suggested_weeks_on_hand DECIMAL,
    hot_deals INTEGER,
    transfer_from_code TEXT,
    conditional_status TEXT,
    challenge_status TEXT,
    last_date_modified TIMESTAMP,
    pounds DECIMAL,
    siq_order_policy TEXT,
    PRIMARY KEY (source_db, location_code, item_no_, variant_code)
);

-- =============================================================================
-- Table 11: vendor
-- =============================================================================
CREATE TABLE dw2_nav.vendor (
    source_db TEXT NOT NULL,
    hash TEXT,
    no_ TEXT NOT NULL,
    name TEXT,
    search_name TEXT,
    name_2 TEXT,
    address TEXT,
    address_2 TEXT,
    city TEXT,
    contact TEXT,
    phone_no_ TEXT,
    our_account_no_ TEXT,
    global_dimension_1_code TEXT,
    global_dimension_2_code TEXT,
    vendor_posting_group TEXT,
    payment_terms_code TEXT,
    purchaser_code TEXT,
    shipment_method_code TEXT,
    invoice_disc_code TEXT,
    blocked INTEGER,
    pay_to_vendor_no_ TEXT,
    priority INTEGER,
    payment_method_code TEXT,
    gen_bus_posting_group TEXT,
    post_code TEXT,
    county TEXT,
    e_mail TEXT,
    home_page TEXT,
    primary_contact_no_ TEXT,
    location_code TEXT,
    lead_time_calculation VARCHAR(32),
    payment_terms_id TEXT,
    payment_method_id TEXT,
    federal_id_no_ TEXT,
    unipro_supplier INTEGER,
    duns_bradstreet_no_ TEXT,
    default_g_l_account TEXT,
    maximum_order_amount DECIMAL,
    default_delivery TEXT,
    geographic_code TEXT,
    default_fee_for_service DECIMAL,
    vendor_group_code TEXT,
    commodity_manufacturer_code TEXT,
    rebate_doc_handling INTEGER,
    vendor_class TEXT,
    ap_rep TEXT,
    legacy_no_ TEXT,
    external_no_ TEXT,
    certified_organic INTEGER,
    small_business_enterprise_sbe INTEGER,
    minority_owned_mbe INTEGER,
    woman_owned_wbe INTEGER,
    veteran_owned_vosb INTEGER,
    disab_owned_bus_ent_dobe INTEGER,
    family_owned_business INTEGER,
    vendor_credit_limit DECIMAL,
    PRIMARY KEY (source_db, no_)
);

-- =============================================================================
-- Table 12: sales_header
-- =============================================================================
CREATE TABLE dw2_nav.sales_header (
    source_db TEXT NOT NULL,
    hash TEXT,
    document_type INTEGER NOT NULL,
    no_ TEXT NOT NULL,
    sell_to_customer_no_ TEXT,
    bill_to_customer_no_ TEXT,
    bill_to_name TEXT,
    bill_to_name_2 TEXT,
    bill_to_address TEXT,
    bill_to_address_2 TEXT,
    bill_to_city TEXT,
    bill_to_contact TEXT,
    ship_to_name TEXT,
    ship_to_name_2 TEXT,
    ship_to_address TEXT,
    ship_to_address_2 TEXT,
    ship_to_city TEXT,
    ship_to_contact TEXT,
    order_date TIMESTAMP,
    posting_date TIMESTAMP,
    shipment_date TIMESTAMP,
    posting_description TEXT,
    payment_terms_code TEXT,
    due_date TIMESTAMP,
    pmt_discount_date TIMESTAMP,
    shipment_method_code TEXT,
    location_code TEXT,
    shortcut_dimension_1_code TEXT,
    shortcut_dimension_2_code TEXT,
    customer_posting_group TEXT,
    invoice_disc_code TEXT,
    salesperson_code TEXT,
    sell_to_customer_name TEXT,
    sell_to_customer_name_2 TEXT,
    sell_to_address TEXT,
    sell_to_address_2 TEXT,
    sell_to_city TEXT,
    sell_to_contact TEXT,
    bill_to_post_code TEXT,
    bill_to_county TEXT,
    bill_to_country_region_code TEXT,
    sell_to_post_code TEXT,
    sell_to_county TEXT,
    sell_to_country_region_code TEXT,
    ship_to_post_code TEXT,
    ship_to_county TEXT,
    ship_to_country_region_code TEXT,
    document_date TIMESTAMP,
    external_document_no_ TEXT,
    payment_method_code TEXT,
    assigned_user_id TEXT,
    original_invoice_no_ TEXT,
    order_type TEXT,
    csr TEXT,
    customer_order_no_ TEXT,
    price_at_shipment INTEGER,
    route_no_ TEXT,
    stop_no_ TEXT,
    sodexo_customer INTEGER,
    order_date_time TIMESTAMP,
    special_instructions TEXT,
    drop_ship_po_no_ TEXT,
    vendor_sample INTEGER,
    gsf_sample INTEGER,
    route_error INTEGER,
    driver TEXT,
    last_page_no_ INTEGER,
    invoice_type TEXT,
    true_posting_date_time TIMESTAMP,
    edi_order BOOLEAN,
    edi_internal_doc_no_ TEXT,
    edi_invoice_generated BOOLEAN,
    edi_inv_gen_date TIMESTAMP,
    edi_ack_generated INTEGER,
    edi_ack_gen_date TIMESTAMP,
    edi_whse_shp_gen INTEGER,
    edi_whse_shp_gen_date TIMESTAMP,
    edi_trade_partner TEXT,
    edi_sell_to_code TEXT,
    edi_ship_to_code TEXT,
    edi_ship_for_code TEXT,
    edi_invoice INTEGER,
    edi_transaction_date TIMESTAMP,
    edi_transaction_time TIMESTAMP,
    online_order_no_ TEXT,
    pas_override_reason TEXT,
    original_order_no_ TEXT,
    customer_po_2 TEXT,
    rebate_start_date TIMESTAMP,
    rebate_end_date TIMESTAMP,
    PRIMARY KEY (source_db, document_type, no_)
);

-- =============================================================================
-- Table 13: sales_invoice_header
-- =============================================================================
CREATE TABLE dw2_nav.sales_invoice_header (
    source_db TEXT NOT NULL,
    hash TEXT,
    no_ TEXT NOT NULL,
    sell_to_customer_no_ TEXT,
    bill_to_customer_no_ TEXT,
    bill_to_name TEXT,
    bill_to_name_2 TEXT,
    bill_to_address TEXT,
    bill_to_address_2 TEXT,
    bill_to_city TEXT,
    bill_to_contact TEXT,
    ship_to_name TEXT,
    ship_to_name_2 TEXT,
    ship_to_address TEXT,
    ship_to_address_2 TEXT,
    ship_to_city TEXT,
    ship_to_contact TEXT,
    order_date TIMESTAMP,
    posting_date TIMESTAMP,
    shipment_date TIMESTAMP,
    posting_description TEXT,
    payment_terms_code TEXT,
    due_date TIMESTAMP,
    shipment_method_code TEXT,
    location_code TEXT,
    shortcut_dimension_1_code TEXT,
    shortcut_dimension_2_code TEXT,
    customer_posting_group TEXT,
    customer_price_group TEXT,
    invoice_disc_code TEXT,
    salesperson_code TEXT,
    order_no_ TEXT,
    no_printed INTEGER,
    reason_code TEXT,
    gen_bus_posting_group TEXT,
    sell_to_customer_name TEXT,
    sell_to_customer_name_2 TEXT,
    sell_to_address TEXT,
    sell_to_address_2 TEXT,
    sell_to_city TEXT,
    sell_to_contact TEXT,
    bill_to_post_code TEXT,
    bill_to_county TEXT,
    sell_to_post_code TEXT,
    sell_to_county TEXT,
    ship_to_post_code TEXT,
    ship_to_county TEXT,
    document_date TIMESTAMP,
    external_document_no_ TEXT,
    shipping_agent_code TEXT,
    no_series TEXT,
    user_id TEXT,
    source_code TEXT,
    tax_area_code TEXT,
    tax_liable BOOLEAN,
    dimension_set_id INTEGER,
    cust_ledger_entry_no_ INTEGER,
    campaign_no_ TEXT,
    sell_to_contact_no_ TEXT,
    bill_to_contact_no_ TEXT,
    opportunity_no_ TEXT,
    responsibility_center TEXT,
    allow_line_disc_ BOOLEAN,
    original_invoice_no_ TEXT,
    created_from_credit_no_ TEXT,
    rebate_type INTEGER,
    rebate_start_date TIMESTAMP,
    PRIMARY KEY (source_db, no_)
);

-- =============================================================================
-- Table 14: sales_line
-- =============================================================================
CREATE TABLE dw2_nav.sales_line (
    source_db TEXT NOT NULL,
    hash TEXT,
    document_type INTEGER NOT NULL,
    document_no_ TEXT NOT NULL,
    line_no_ INTEGER NOT NULL,
    sell_to_customer_no_ TEXT,
    type INTEGER,
    no_ TEXT,
    location_code TEXT,
    posting_group TEXT,
    shipment_date TIMESTAMP,
    description TEXT,
    description_2 TEXT,
    unit_of_measure TEXT,
    quantity DECIMAL,
    unit_price DECIMAL,
    unit_cost_lcy DECIMAL,
    vat_ DECIMAL,
    line_discount_ DECIMAL,
    line_discount_amount DECIMAL,
    amount DECIMAL,
    amount_including_vat DECIMAL,
    allow_invoice_disc_ BOOLEAN,
    gross_weight DECIMAL,
    net_weight DECIMAL,
    units_per_parcel DECIMAL,
    unit_volume DECIMAL,
    shortcut_dimension_1_code TEXT,
    shortcut_dimension_2_code TEXT,
    bill_to_customer_no_ TEXT,
    gen_bus_posting_group TEXT,
    gen_prod_posting_group TEXT,
    vat_calculation_type INTEGER,
    attached_to_line_no_ INTEGER,
    tax_area_code TEXT,
    tax_liable BOOLEAN,
    tax_group_code TEXT,
    vat_base_amount DECIMAL,
    unit_cost DECIMAL,
    line_amount DECIMAL,
    vat_difference DECIMAL,
    dimension_set_id INTEGER,
    variant_code TEXT,
    bin_code TEXT,
    qty_per_unit_of_measure DECIMAL,
    unit_of_measure_code TEXT,
    quantity_base DECIMAL,
    item_category_code TEXT,
    product_group_code TEXT,
    return_reason_code TEXT,
    allow_line_disc_ BOOLEAN,
    do_not_print INTEGER,
    contract_price INTEGER,
    order_type TEXT,
    price_coop_no_ TEXT,
    commodity_line_type INTEGER,
    commodity_line_for_line_no_ INTEGER,
    commodity_kit_qty_base DECIMAL,
    edi_uom TEXT,
    crv_related_to_line_no_ INTEGER,
    short_ship_reason_code TEXT,
    item_substituted INTEGER,
    item_substitute_item_no_ TEXT,
    substitute_line_number INTEGER,
    substitute_item_line_no_ INTEGER,
    substitute_for_item_no_ TEXT,
    substitution_reason_code TEXT,
    zone TEXT,
    vendor_sample INTEGER,
    gsf_sample INTEGER,
    vendor_group_code TEXT,
    commodity_amount DECIMAL,
    commodity_lbs DECIMAL,
    dont_use_commodity INTEGER,
    price_id INTEGER,
    do_not_pick INTEGER,
    qty_to_pick DECIMAL,
    original_quantity DECIMAL,
    item_vendor_no_ TEXT,
    lot_no_ TEXT,
    co_op_district_quantity_code TEXT,
    co_op_district_amount_code TEXT,
    skipped_lead_time_check INTEGER,
    pounds DECIMAL,
    price_per_pound DECIMAL,
    package_quantity DECIMAL,
    substitute_for_order_no_ TEXT,
    hot_deals INTEGER,
    outstanding_quantity DECIMAL,
    PRIMARY KEY (source_db, document_type, document_no_, line_no_)
);
