import * as cdk from "aws-cdk-lib";
import * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import { Construct } from "constructs";
import {
  NamingConfig,
  createNamingHelper,
  ResourceTypes,
} from "../config/naming";
import { addStandardTags } from "../config/tags";

export interface SecretsConstructProps {
  envName: string;
  naming: NamingConfig;
}

/**
 * Construct for managing external database secrets (DMS sources, etc.)
 * Aurora secret remains auto-generated by RDS - this is for external systems only.
 */
export class SecretsConstruct extends Construct {
  public readonly dw2Secret: secretsmanager.Secret;
  public readonly siqSecret: secretsmanager.Secret;
  public readonly jiraSecret: secretsmanager.Secret;

  constructor(scope: Construct, id: string, props: SecretsConstructProps) {
    super(scope, id);

    const { envName, naming } = props;

    // Generate resource names
    const n = createNamingHelper(naming);
    const dw2SecretName = n.name(ResourceTypes.SECRETS_MANAGER, "dw2", "01");

    // DW2 SQL Server secret (DMS source)
    // Password is a placeholder - update manually after deployment
    this.dw2Secret = new secretsmanager.Secret(this, "Dw2Secret", {
      secretName: dw2SecretName,
      description: `${envName.toUpperCase()} - DW2 SQL Server connection (DMS source)`,
      secretObjectValue: {
        host: cdk.SecretValue.unsafePlainText("10.200.6.172"),
        port: cdk.SecretValue.unsafePlainText("1433"),
        database: cdk.SecretValue.unsafePlainText("DW2"),
        username: cdk.SecretValue.unsafePlainText("SysAI"),
        password: cdk.SecretValue.unsafePlainText(
          "PLACEHOLDER_UPDATE_MANUALLY"
        ),
      },
    });

    // Tags
    addStandardTags(this.dw2Secret, naming.env, dw2SecretName);

    // Stock IQ API secret (basic auth)
    // Username and password are placeholders - update manually after deployment
    const siqSecretName = n.name(ResourceTypes.SECRETS_MANAGER, "siq", "01");
    this.siqSecret = new secretsmanager.Secret(this, "SiqSecret", {
      secretName: siqSecretName,
      description: `${envName.toUpperCase()} - Stock IQ API credentials`,
      secretObjectValue: {
        username: cdk.SecretValue.unsafePlainText(
          "PLACEHOLDER_UPDATE_MANUALLY"
        ),
        password: cdk.SecretValue.unsafePlainText(
          "PLACEHOLDER_UPDATE_MANUALLY"
        ),
      },
    });

    addStandardTags(this.siqSecret, naming.env, siqSecretName);

    // Jira API secret (email + API token for issue reporting)
    // Credentials are placeholders - update manually after deployment
    const jiraSecretName = n.name(ResourceTypes.SECRETS_MANAGER, "jira", "01");
    this.jiraSecret = new secretsmanager.Secret(this, "JiraSecret", {
      secretName: jiraSecretName,
      description: `${envName.toUpperCase()} - Jira API credentials (issue reporting)`,
      secretObjectValue: {
        email: cdk.SecretValue.unsafePlainText("PLACEHOLDER_UPDATE_MANUALLY"),
        apiToken: cdk.SecretValue.unsafePlainText(
          "PLACEHOLDER_UPDATE_MANUALLY"
        ),
        baseUrl: cdk.SecretValue.unsafePlainText(
          "https://gsfoodsgroup.atlassian.net"
        ),
        projectKey: cdk.SecretValue.unsafePlainText("ATV"),
      },
    });

    addStandardTags(this.jiraSecret, naming.env, jiraSecretName);
  }
}
