-- CreateTable
CREATE TABLE "dw2_nav"."contact" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "name" TEXT,
    "search_name" TEXT,
    "name_2" TEXT,
    "address" TEXT,
    "address_2" TEXT,
    "city" TEXT,
    "phone_no_" TEXT,
    "salesperson_code" TEXT,
    "fax_no_" TEXT,
    "post_code" TEXT,
    "county" TEXT,
    "e_mail" TEXT,
    "home_page" TEXT,
    "no_series" TEXT,
    "type" INTEGER,
    "company_no_" TEXT,
    "company_name" TEXT,
    "first_name" TEXT,
    "middle_name" TEXT,
    "surname" TEXT,
    "job_title" TEXT,
    "mobile_phone_no_" TEXT,
    "pager" TEXT,
    "organizational_level_code" TEXT,
    "exclude_from_segment" INTEGER,
    "search_e_mail" TEXT,
    "e_mail_2" TEXT,

    CONSTRAINT "contact_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."segment_header" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "description" TEXT,
    "campaign_no_" TEXT,
    "salesperson_code" TEXT,
    "correspondence_type_default" INTEGER,
    "interaction_template_code" TEXT,
    "unit_cost_lcy" DECIMAL(65,30),
    "unit_duration_min_" DECIMAL(65,30),
    "date" TIMESTAMP(3),
    "campaign_target" INTEGER,
    "information_flow" INTEGER,
    "initiated_by" INTEGER,
    "no_series" TEXT,
    "campaign_response" INTEGER,
    "language_code_default" TEXT,
    "interaction_group_code" TEXT,
    "send_word_docs_as_attmt_" INTEGER,
    "ignore_contact_corres_type" INTEGER,
    "subject_default" TEXT,

    CONSTRAINT "segment_header_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."segment_line" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "segment_no_" TEXT NOT NULL,
    "line_no_" INTEGER NOT NULL,
    "contact_no_" TEXT,
    "campaign_no_" TEXT,
    "salesperson_code" TEXT,
    "correspondence_type" INTEGER,
    "interaction_template_code" TEXT,
    "cost_lcy" DECIMAL(65,30),
    "duration_min_" DECIMAL(65,30),
    "attachment_no_" INTEGER,
    "campaign_response" INTEGER,
    "information_flow" INTEGER,
    "initiated_by" INTEGER,
    "contact_alt_address_code" TEXT,
    "evaluation" INTEGER,
    "campaign_target" INTEGER,
    "language_code" TEXT,
    "description" TEXT,
    "date" TIMESTAMP(3),
    "time_of_interaction" TIMESTAMP(3),
    "attempt_failed" INTEGER,
    "to_do_no_" TEXT,
    "contact_company_no_" TEXT,
    "campaign_entry_no_" INTEGER,
    "interaction_group_code" TEXT,
    "document_type" INTEGER,
    "document_no_" TEXT,
    "send_word_doc_as_attmt_" INTEGER,
    "contact_via" TEXT,
    "version_no_" INTEGER,
    "doc_no_occurrence" INTEGER,
    "subject" TEXT,
    "opportunity_no_" TEXT,
    "wizard_step" INTEGER,
    "wizard_contact_name" TEXT,
    "opportunity_description" TEXT,
    "campaign_description" TEXT,
    "interaction_successful" INTEGER,
    "dial_contact" INTEGER,
    "mail_contact" INTEGER,

    CONSTRAINT "segment_line_pkey" PRIMARY KEY ("source_db","segment_no_","line_no_")
);
