import type { MonthlyForecastDto } from "@/types/monthly-forecast";

export const mockForecastData: MonthlyForecastDto[] = [
  {
    id: "1",
    location: "DORI",
    itemNumber: "ITEM-12345",
    description: "Premium Wireless Headphones",
    threeMonthAvgActuals: 150,
    currentActuals: 153,
    lastYearNextMonthActuals: 140,
    nextMonthForecast: 231,
    monthPlus2Forecast: 249,
    monthPlus3Forecast: 261,
    variancePercent: -35.1,
    adjustedForecast: 150,
    top5Customers: [
      "Hospitality Group LLC",
      "Premium Catering Co",
      "Casual Dining Chain",
      "University Dining Services",
      "ABC Retail Store",
    ],
    dpNotes: "Reviewed and approved. Increase stock levels.",
  },
  {
    id: "2",
    location: "FW",
    itemNumber: "ITEM-67890",
    description: "Ergonomic Office Chair",
    threeMonthAvgActuals: 80,
    currentActuals: 80,
    lastYearNextMonthActuals: 81,
    nextMonthForecast: 50,
    monthPlus2Forecast: 54,
    monthPlus3Forecast: 57,
    variancePercent: 60.0,
    adjustedForecast: 80,
    top5Customers: [
      "XYZ Electronics",
      "Global Office Supplies",
      "Metro Food Services",
      "Quick Serve Restaurants",
      "Casual Dining Chain",
    ],
    dpNotes: null,
  },
  {
    id: "3",
    location: "GSF",
    itemNumber: "ITEM-11111",
    description: "Professional Notebook Set",
    threeMonthAvgActuals: 120,
    currentActuals: 116,
    lastYearNextMonthActuals: 131,
    nextMonthForecast: 200,
    monthPlus2Forecast: 216,
    monthPlus3Forecast: 227,
    variancePercent: -40.0,
    adjustedForecast: 120,
    top5Customers: [
      "School District Food Program",
      "Campus Dining Solutions",
      "University Dining Services",
      "Healthcare Food Services",
      "Premium Catering Co",
    ],
    dpNotes: null,
  },
  {
    id: "4",
    location: "JC",
    itemNumber: "ITEM-22222",
    description: "Frozen Pizza Pepperoni 12ct",
    threeMonthAvgActuals: 450,
    currentActuals: 437,
    lastYearNextMonthActuals: 527,
    nextMonthForecast: 290,
    monthPlus2Forecast: 313,
    monthPlus3Forecast: 329,
    variancePercent: 55.2,
    adjustedForecast: 450,
    top5Customers: [
      "Quick Serve Restaurants",
      "Casual Dining Chain",
      "Metro Food Services",
      "Hospitality Group LLC",
      "ABC Retail Store",
    ],
    dpNotes: "Review pricing strategy. Consider promotions.",
  },
  {
    id: "5",
    location: "MA",
    itemNumber: "ITEM-33333",
    description: "Chicken Wings Hot & Spicy 40lb",
    threeMonthAvgActuals: 320,
    currentActuals: 329,
    lastYearNextMonthActuals: 272,
    nextMonthForecast: 457,
    monthPlus2Forecast: 494,
    monthPlus3Forecast: 519,
    variancePercent: -30.0,
    adjustedForecast: 320,
    top5Customers: [
      "Metro Food Services",
      "Campus Dining Solutions",
      "Quick Serve Restaurants",
      "School District Food Program",
      "Healthcare Food Services",
    ],
    dpNotes: "Significant underforecast. Increase allocation immediately.",
  },
  {
    id: "6",
    location: "MO",
    itemNumber: "ITEM-44444",
    description: "French Fries Crinkle Cut 6/5lb",
    threeMonthAvgActuals: 280,
    currentActuals: 287,
    lastYearNextMonthActuals: 260,
    nextMonthForecast: 193,
    monthPlus2Forecast: 208,
    monthPlus3Forecast: 218,
    variancePercent: 45.1,
    adjustedForecast: 280,
    top5Customers: [
      "Hospitality Group LLC",
      "Premium Catering Co",
      "Casual Dining Chain",
      "University Dining Services",
      "ABC Retail Store",
    ],
    dpNotes: "Monitor competitor activity. Risk of account loss.",
  },
  {
    id: "7",
    location: "NC",
    itemNumber: "ITEM-55555",
    description: "Cheese Mozzarella Shredded 4/5lb",
    threeMonthAvgActuals: 520,
    currentActuals: 525,
    lastYearNextMonthActuals: 525,
    nextMonthForecast: 722,
    monthPlus2Forecast: 780,
    monthPlus3Forecast: 819,
    variancePercent: -28.0,
    adjustedForecast: 520,
    top5Customers: [
      "XYZ Electronics",
      "Global Office Supplies",
      "Metro Food Services",
      "Quick Serve Restaurants",
      "Casual Dining Chain",
    ],
    dpNotes: "Strong growth trend. Verify warehouse capacity.",
  },
  {
    id: "8",
    location: "NWD",
    itemNumber: "ITEM-66666",
    description: "Ground Beef 80/20 10lb Chubs",
    threeMonthAvgActuals: 180,
    currentActuals: 171,
    lastYearNextMonthActuals: 196,
    nextMonthForecast: 118,
    monthPlus2Forecast: 127,
    monthPlus3Forecast: 133,
    variancePercent: 52.5,
    adjustedForecast: 180,
    top5Customers: [
      "School District Food Program",
      "Campus Dining Solutions",
      "University Dining Services",
      "Healthcare Food Services",
      "Premium Catering Co",
    ],
    dpNotes: "Overforecast situation. Adjust inventory levels down.",
  },
  {
    id: "9",
    location: "PA",
    itemNumber: "ITEM-77777",
    description: "Salmon Fillets Atlantic 10lb",
    threeMonthAvgActuals: 420,
    currentActuals: 411,
    lastYearNextMonthActuals: 491,
    nextMonthForecast: 677,
    monthPlus2Forecast: 731,
    monthPlus3Forecast: 768,
    variancePercent: -38.0,
    adjustedForecast: 420,
    top5Customers: [
      "Quick Serve Restaurants",
      "Casual Dining Chain",
      "Metro Food Services",
      "Hospitality Group LLC",
      "ABC Retail Store",
    ],
    dpNotes: "Excellent performance. Consider premium pricing tier.",
  },
  {
    id: "10",
    location: "RC",
    itemNumber: "ITEM-88888",
    description: "Turkey Breast Roasted 2/8lb",
    threeMonthAvgActuals: 95,
    currentActuals: 93,
    lastYearNextMonthActuals: 81,
    nextMonthForecast: 64,
    monthPlus2Forecast: 69,
    monthPlus3Forecast: 72,
    variancePercent: 48.4,
    adjustedForecast: 95,
    top5Customers: [
      "Metro Food Services",
      "Campus Dining Solutions",
      "Quick Serve Restaurants",
      "School District Food Program",
      "Healthcare Food Services",
    ],
    dpNotes: "Major variance alert. Contract negotiation in progress.",
  },
  {
    id: "11",
    location: "SC",
    itemNumber: "ITEM-99999",
    description: "Bacon Sliced Applewood 15lb",
    threeMonthAvgActuals: 380,
    currentActuals: 385,
    lastYearNextMonthActuals: 353,
    nextMonthForecast: 559,
    monthPlus2Forecast: 604,
    monthPlus3Forecast: 634,
    variancePercent: -32.0,
    adjustedForecast: 380,
    top5Customers: [
      "Hospitality Group LLC",
      "Premium Catering Co",
      "Casual Dining Chain",
      "University Dining Services",
      "ABC Retail Store",
    ],
    dpNotes: "Strong upward trend. Allocate additional capacity.",
  },
  {
    id: "12",
    location: "DORI",
    itemNumber: "ITEM-10101",
    description: "Pasta Penne Rigate 20lb",
    threeMonthAvgActuals: 240,
    currentActuals: 239,
    lastYearNextMonthActuals: 242,
    nextMonthForecast: 160,
    monthPlus2Forecast: 173,
    monthPlus3Forecast: 182,
    variancePercent: 50.0,
    adjustedForecast: 240,
    top5Customers: [
      "XYZ Electronics",
      "Global Office Supplies",
      "Metro Food Services",
      "Quick Serve Restaurants",
      "Casual Dining Chain",
    ],
    dpNotes: "Seasonal adjustment needed. Track weekly.",
  },
];
