-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "dw2_nav";

-- CreateTable
CREATE TABLE "dw2_nav"."acc_schedule_line" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "schedule_name" TEXT NOT NULL,
    "line_no_" INTEGER NOT NULL,
    "row_no_" TEXT,
    "description" TEXT,
    "totaling" TEXT,
    "totaling_type" INTEGER,
    "new_page" BOOLEAN,
    "indentation" INTEGER,
    "show" INTEGER,
    "dimension_1_totaling" TEXT,
    "dimension_2_totaling" TEXT,
    "dimension_3_totaling" TEXT,
    "dimension_4_totaling" TEXT,
    "bold" BOOLEAN,
    "italic" BOOLEAN,
    "underline" BOOLEAN,
    "show_opposite_sign" BOOLEAN,
    "row_type" INTEGER,
    "amount_type" INTEGER,
    "double_underline" BOOLEAN,
    "cost_center_totaling" TEXT,
    "cost_object_totaling" TEXT,

    CONSTRAINT "acc_schedule_line_pkey" PRIMARY KEY ("source_db","schedule_name","line_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."accounting_period" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "starting_date" TIMESTAMP(3) NOT NULL,
    "name" TEXT,
    "new_fiscal_year" BOOLEAN,
    "closed" BOOLEAN,
    "date_locked" BOOLEAN,
    "average_cost_calc_type" INTEGER,
    "average_cost_period" INTEGER,

    CONSTRAINT "accounting_period_pkey" PRIMARY KEY ("source_db","starting_date")
);

-- CreateTable
CREATE TABLE "dw2_nav"."appointment_schedule" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "location_code" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "time" TIMESTAMP(3) NOT NULL,
    "document_no_" TEXT,
    "vendor_name" TEXT,
    "user_id" TEXT,

    CONSTRAINT "appointment_schedule_pkey" PRIMARY KEY ("source_db","location_code","code","date","time")
);

-- CreateTable
CREATE TABLE "dw2_nav"."bid_header" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "standard_markup" INTEGER,
    "bid_type" INTEGER,
    "markup_cost" INTEGER,
    "fixed_price" BOOLEAN,
    "starting_date" TIMESTAMP(3),
    "ending_date" TIMESTAMP(3),

    CONSTRAINT "bid_header_pkey" PRIMARY KEY ("source_db","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."bid_line" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "code" TEXT NOT NULL,
    "item_type" INTEGER NOT NULL,
    "item_code" TEXT NOT NULL,
    "starting_date" TIMESTAMP(3) NOT NULL,
    "ending_date" TIMESTAMP(3) NOT NULL,
    "standard_markup" INTEGER,
    "bid_type" INTEGER,
    "markup_cost" INTEGER,
    "fixed_price" BOOLEAN,
    "markup_amount" DECIMAL(65,30),
    "current_price" DECIMAL(65,30),
    "future_price" DECIMAL(65,30),
    "actual_cost" DECIMAL(65,30),
    "allowance_per_case" DECIMAL(65,30),
    "break_case_upcharge" DECIMAL(65,30),
    "current_break_case_price" DECIMAL(65,30),
    "future_break_case_price" DECIMAL(65,30),
    "change_code" TEXT,
    "cost_type" INTEGER,
    "sales_rep_cost_overide" DECIMAL(65,30),
    "locked" BOOLEAN,
    "commodity_markup_amount" DECIMAL(65,30),
    "commodity_break_case_upcharge" DECIMAL(65,30),

    CONSTRAINT "bid_line_pkey" PRIMARY KEY ("source_db","code","item_type","item_code","starting_date","ending_date")
);

-- CreateTable
CREATE TABLE "dw2_nav"."bin" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "location_code" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "zone_code" TEXT,
    "bin_type_code" TEXT,
    "warehouse_class_code" TEXT,
    "block_movement" INTEGER,
    "special_equipment_code" TEXT,
    "bin_ranking" INTEGER,
    "maximum_cubage" DECIMAL(65,30),
    "maximum_weight" DECIMAL(65,30),
    "empty" BOOLEAN,
    "cross_dock_bin" INTEGER,
    "dedicated" BOOLEAN,
    "aisle" INTEGER,
    "side" INTEGER,
    "position" INTEGER,
    "level" INTEGER,
    "distance" INTEGER,
    "bin_size" DECIMAL(65,30),
    "bin_height" DECIMAL(65,30),
    "dummy_bin" INTEGER,
    "wave_pick_bin" BOOLEAN,
    "bin_sorting" INTEGER,
    "pallet_bin" INTEGER,
    "pallet_counting_period" TEXT,
    "last_counted_date" TIMESTAMP(3),
    "pallet_count_ranking" INTEGER,
    "included_in_quick_count" BOOLEAN,
    "drop_bin" INTEGER,
    "linked_to_drop_bin" TEXT,
    "last_counted_datetime" TIMESTAMP(3),
    "default_replenishment_rule" TEXT,
    "pallet_type" TEXT,

    CONSTRAINT "bin_pkey" PRIMARY KEY ("source_db","location_code","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."bin_content" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "location_code" TEXT NOT NULL,
    "bin_code" TEXT NOT NULL,
    "item_no_" TEXT NOT NULL,
    "variant_code" TEXT NOT NULL,
    "unit_of_measure_code" TEXT NOT NULL,
    "zone_code" TEXT,
    "bin_type_code" TEXT,
    "warehouse_class_code" TEXT,
    "block_movement" INTEGER,
    "min_qty" DECIMAL(65,30),
    "max_qty" DECIMAL(65,30),
    "bin_ranking" INTEGER,
    "fixed" BOOLEAN,
    "cross_dock_bin" INTEGER,
    "default" BOOLEAN,
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "dedicated" BOOLEAN,
    "replen_user" TEXT,
    "source_no_" TEXT,
    "bin_sorting" INTEGER,
    "license_plate_ranking" INTEGER,
    "replenishment_rule" TEXT,

    CONSTRAINT "bin_content_pkey" PRIMARY KEY ("source_db","location_code","bin_code","item_no_","variant_code","unit_of_measure_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."bin_type" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "code" TEXT NOT NULL,
    "description" TEXT,
    "receive" BOOLEAN,
    "ship" BOOLEAN,
    "put_away" BOOLEAN,
    "pick" BOOLEAN,
    "pallet_pick" BOOLEAN,
    "special_order" INTEGER,

    CONSTRAINT "bin_type_pkey" PRIMARY KEY ("source_db","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."campaign" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "description" TEXT,
    "starting_date" TIMESTAMP(3),
    "ending_date" TIMESTAMP(3),
    "salesperson_code" TEXT,
    "last_date_modified" TIMESTAMP(3),
    "no_series" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "status_code" TEXT,
    "price_sequence" INTEGER,
    "location_code" TEXT,

    CONSTRAINT "campaign_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."campaign_target_group" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "type" INTEGER NOT NULL,
    "no_" TEXT NOT NULL,
    "campaign_no_" TEXT NOT NULL,
    "price_sequence" INTEGER,

    CONSTRAINT "campaign_target_group_pkey" PRIMARY KEY ("source_db","type","no_","campaign_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."co_op_distributor_transaction" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "manufacturer_code" TEXT NOT NULL,
    "recipient_agency_no_" TEXT NOT NULL,
    "document_no_" TEXT NOT NULL,
    "document_line_no_" TEXT NOT NULL,
    "manufacture_item_no_" TEXT NOT NULL,
    "document_type" TEXT NOT NULL,
    "reported_by" TEXT,
    "document_date" TIMESTAMP(3),
    "quantity" DECIMAL(65,30),
    "distributor_name" TEXT,
    "bill_to_customer_no_" TEXT,
    "nav_vendor_no_" TEXT,
    "nav_item_no_" TEXT,
    "line_import_error" BOOLEAN,
    "error_message" TEXT,
    "date_imported" TIMESTAMP(3),
    "time_imported" TIMESTAMP(3),
    "imported_by" TEXT,
    "date_processed" TIMESTAMP(3),
    "time_processed" TIMESTAMP(3),
    "posted_by" TEXT,
    "import_filename" TEXT,
    "distributor_name_modified" TEXT,
    "commodity_ledger_entry_no_" INTEGER,
    "entry_no_" INTEGER,

    CONSTRAINT "co_op_distributor_transaction_pkey" PRIMARY KEY ("source_db","manufacturer_code","recipient_agency_no_","document_no_","document_line_no_","manufacture_item_no_","document_type")
);

-- CreateTable
CREATE TABLE "dw2_nav"."commodity_amt_limit" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "co_op_district_amt_code" TEXT NOT NULL,

    CONSTRAINT "commodity_amt_limit_pkey" PRIMARY KEY ("source_db","co_op_district_amt_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."commodity_component" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "parent_item_no_" TEXT NOT NULL,
    "vendor_no_" TEXT NOT NULL,
    "line_no_" INTEGER NOT NULL,
    "item_no_" TEXT,
    "unit_of_measure_code" TEXT NOT NULL,
    "yield" DECIMAL(65,30),
    "net_off_invoice_amount" DECIMAL(65,30),

    CONSTRAINT "commodity_component_pkey" PRIMARY KEY ("source_db","parent_item_no_","vendor_no_","line_no_","unit_of_measure_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."commodity_lb_limit" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "co_op_district_quantity_code" TEXT NOT NULL,
    "vendor_group_code" TEXT NOT NULL,
    "item_no_" TEXT NOT NULL,

    CONSTRAINT "commodity_lb_limit_pkey" PRIMARY KEY ("source_db","co_op_district_quantity_code","vendor_group_code","item_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."commodity_opt_out" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "co_op_district_group_code" TEXT NOT NULL,
    "vendor_group_code" TEXT NOT NULL,
    "item_no_" TEXT NOT NULL,
    "type" INTEGER,

    CONSTRAINT "commodity_opt_out_pkey" PRIMARY KEY ("source_db","co_op_district_group_code","vendor_group_code","item_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."default_dimension" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "table_id" INTEGER NOT NULL,
    "no_" TEXT NOT NULL,
    "dimension_code" TEXT NOT NULL,
    "dimension_value_code" TEXT,
    "value_posting" INTEGER,
    "multi_selection_action" INTEGER,

    CONSTRAINT "default_dimension_pkey" PRIMARY KEY ("source_db","table_id","no_","dimension_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."delivery_schedule" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "type" INTEGER NOT NULL,
    "source_no_" TEXT NOT NULL,
    "order_type" TEXT NOT NULL,
    "monday" BOOLEAN,
    "tuesday" BOOLEAN,
    "wednesday" BOOLEAN,
    "thursday" BOOLEAN,
    "friday" BOOLEAN,
    "saturday" BOOLEAN,
    "sunday" BOOLEAN,
    "minimum_order_amount" DECIMAL(65,30),
    "lead_time" INTEGER,
    "back_date_in_days" INTEGER,
    "csr" TEXT,
    "first_week" BOOLEAN,
    "second_week" BOOLEAN,
    "third_week" BOOLEAN,
    "fourth_week" BOOLEAN,
    "last_week" BOOLEAN,

    CONSTRAINT "delivery_schedule_pkey" PRIMARY KEY ("source_db","type","source_no_","order_type")
);

-- CreateTable
CREATE TABLE "dw2_nav"."dimension_set_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "dimension_set_id" INTEGER NOT NULL,
    "dimension_code" TEXT NOT NULL,
    "dimension_value_code" TEXT,
    "dimension_value_id" INTEGER,

    CONSTRAINT "dimension_set_entry_pkey" PRIMARY KEY ("source_db","dimension_set_id","dimension_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."dimension_value" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "dimension_code" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT,
    "dimension_value_type" INTEGER,
    "totaling" TEXT,
    "blocked" BOOLEAN,
    "consolidation_code" TEXT,
    "indentation" INTEGER,
    "global_dimension_no_" INTEGER,
    "dimension_value_id" INTEGER,

    CONSTRAINT "dimension_value_pkey" PRIMARY KEY ("source_db","dimension_code","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."lot_no_information" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "item_no_" TEXT NOT NULL,
    "variant_code" TEXT NOT NULL,
    "lot_no_" TEXT NOT NULL,
    "description" TEXT,
    "test_quality" INTEGER,
    "certificate_number" TEXT,
    "blocked" BOOLEAN,
    "initial_quantity" DECIMAL(65,30),
    "posting_date" TIMESTAMP(3),
    "disposition_no_" TEXT,
    "skip_storage_fees" INTEGER,
    "storage_begin_date" TIMESTAMP(3),

    CONSTRAINT "lot_no_information_pkey" PRIMARY KEY ("source_db","item_no_","variant_code","lot_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."pallet_bin_content" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "bin" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "pallet_no_" TEXT NOT NULL,
    "box_no_" TEXT NOT NULL,
    "item_no_" TEXT NOT NULL,
    "variant_no_" TEXT NOT NULL,
    "lot_no_" TEXT NOT NULL,
    "serial_no_" TEXT NOT NULL,
    "unit_of_measure" TEXT NOT NULL,
    "description" TEXT,
    "quantity_base" DECIMAL(65,30),
    "quantity" DECIMAL(65,30),
    "qty_per_uom" DECIMAL(65,30),
    "expiry_date" TIMESTAMP(3),
    "warranty_date" TIMESTAMP(3),
    "last_handled_date" TIMESTAMP(3),
    "last_handled_time" TIMESTAMP(3),
    "creation_date" TIMESTAMP(3),
    "creation_time" TIMESTAMP(3),
    "qa_status" TEXT,
    "source_type" INTEGER,
    "source_sub_type" INTEGER,
    "source_id" TEXT,
    "source_reference_no_" INTEGER,
    "pallet_height" DECIMAL(65,30),
    "counted" BOOLEAN,

    CONSTRAINT "pallet_bin_content_pkey" PRIMARY KEY ("source_db","bin","location","pallet_no_","box_no_","item_no_","variant_no_","lot_no_","serial_no_","unit_of_measure")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item" (
    "validfrom" TIMESTAMP(3),
    "validto" TIMESTAMP(3),
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "no_2" TEXT,
    "description" TEXT,
    "description_2" TEXT,
    "base_unit_of_measure" TEXT,
    "price_unit_conversion" INTEGER,
    "type" INTEGER,
    "inventory_posting_group" TEXT,
    "item_disc_group" TEXT,
    "allow_invoice_disc" BOOLEAN,
    "unit_price" DECIMAL(65,30),
    "price_profit_calculation" INTEGER,
    "profit" DECIMAL(65,30),
    "costing_method" INTEGER,
    "unit_cost" DECIMAL(65,30),
    "last_direct_cost" DECIMAL(65,30),
    "cost_is_adjusted" BOOLEAN,
    "allow_online_adjustment" BOOLEAN,
    "vendor_no_" TEXT,
    "vendor_item_no_" TEXT,
    "lead_time_calculation" VARCHAR(32),
    "reorder_point" DECIMAL(65,30),
    "maximum_inventory" DECIMAL(65,30),
    "reorder_quantity" DECIMAL(65,30),
    "alternative_item_no_" TEXT,
    "unit_list_price" DECIMAL(65,30),
    "gross_weight" DECIMAL(65,30),
    "net_weight" DECIMAL(65,30),
    "units_per_parcel" DECIMAL(65,30),
    "unit_volume" DECIMAL(65,30),
    "country_region_purchased_code" TEXT,
    "blocked" BOOLEAN,
    "block_reason" TEXT,
    "gen_prod_posting_group" TEXT,
    "country_region_of_origin_code" TEXT,
    "reserve" INTEGER,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "lot_size" DECIMAL(65,30),
    "last_unit_cost_calc_date" TIMESTAMP(3),
    "minimum_order_quantity" DECIMAL(65,30),
    "safety_stock_quantity" DECIMAL(65,30),
    "order_multiple" DECIMAL(65,30),
    "safety_lead_time" VARCHAR(32),
    "sales_unit_of_measure" TEXT,
    "purch_unit_of_measure" TEXT,
    "reordering_policy" INTEGER,
    "include_inventory" BOOLEAN,
    "manufacturer_code" TEXT,
    "item_category_code" TEXT,
    "product_group_code" TEXT,
    "phys_invt_counting_period_code" TEXT,
    "last_counting_period_update" TIMESTAMP(3),
    "use_cross_docking" BOOLEAN,
    "next_counting_start_date" TIMESTAMP(3),
    "next_counting_end_date" TIMESTAMP(3),
    "expiration_date_type" INTEGER,
    "expiration_date_rule" INTEGER,
    "buyer_code" TEXT,
    "crv" DECIMAL(65,30),
    "shelf_life_in_days" INTEGER,
    "shelf_life" TEXT,
    "specials_list" INTEGER,
    "sodexo_only" INTEGER,
    "pack_size" TEXT,
    "item_class" TEXT,
    "active_since" TIMESTAMP(3),
    "current_vendor_no_" TEXT,
    "commodity_dependency" INTEGER,
    "commodity_fee_basis" INTEGER,
    "fair_market_value" DECIMAL(65,30),
    "cmdy_value_exception" INTEGER,
    "df_lb_per_case" DECIMAL(65,30),
    "commodity_additional_allowance" DECIMAL(65,30),
    "onelink_order_guide" INTEGER,
    "market_price_item" BOOLEAN,
    "zero_price_allowed" BOOLEAN,
    "zone" TEXT,
    "repack_item_no_" TEXT,
    "repack_qty" DECIMAL(65,30),
    "lb_item_no_" TEXT,
    "master_item_no_" TEXT,
    "master_item" BOOLEAN,
    "njpa" BOOLEAN,
    "always_create_pick" BOOLEAN,
    "status" TEXT,
    "rebate_vendor_no_" TEXT,
    "catch_weight" BOOLEAN,
    "use_unit_of_measure_dimensions" BOOLEAN,
    "producer_of_good_indicator" INTEGER,
    "item_upc_ean_number" TEXT,
    "routing_no_" TEXT,
    "production_bom_no_" TEXT,
    "order_tracking_policy" INTEGER,
    "critical" BOOLEAN,
    "suggested_weeks_on_hand" DECIMAL(65,30),
    "city_state_zip_code_of_origin" TEXT,
    "category_class_code" TEXT,
    "gtin" TEXT,
    "mfg_name" TEXT,
    "non_domestic" BOOLEAN,
    "food_item" BOOLEAN,
    "last_direct_lb_cost" DECIMAL(65,30),
    "exception_type" TEXT,

    CONSTRAINT "item_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_history" (
    "validfrom" TIMESTAMP(3),
    "validto" TIMESTAMP(3),
    "source_db" TEXT,
    "hash" TEXT,
    "no_" TEXT,
    "no_2" TEXT,
    "description" TEXT,
    "description_2" TEXT,
    "base_unit_of_measure" TEXT,
    "price_unit_conversion" INTEGER,
    "type" INTEGER,
    "inventory_posting_group" TEXT,
    "item_disc_group" TEXT,
    "allow_invoice_disc" BOOLEAN,
    "unit_price" DECIMAL(65,30),
    "price_profit_calculation" INTEGER,
    "profit" DECIMAL(65,30),
    "costing_method" INTEGER,
    "unit_cost" DECIMAL(65,30),
    "last_direct_cost" DECIMAL(65,30),
    "cost_is_adjusted" BOOLEAN,
    "allow_online_adjustment" BOOLEAN,
    "vendor_no_" TEXT,
    "vendor_item_no_" TEXT,
    "lead_time_calculation" VARCHAR(32),
    "reorder_point" DECIMAL(65,30),
    "maximum_inventory" DECIMAL(65,30),
    "reorder_quantity" DECIMAL(65,30),
    "alternative_item_no_" TEXT,
    "unit_list_price" DECIMAL(65,30),
    "gross_weight" DECIMAL(65,30),
    "net_weight" DECIMAL(65,30),
    "units_per_parcel" DECIMAL(65,30),
    "unit_volume" DECIMAL(65,30),
    "country_region_purchased_code" TEXT,
    "blocked" BOOLEAN,
    "block_reason" TEXT,
    "gen_prod_posting_group" TEXT,
    "country_region_of_origin_code" TEXT,
    "reserve" INTEGER,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "lot_size" DECIMAL(65,30),
    "last_unit_cost_calc_date" TIMESTAMP(3),
    "minimum_order_quantity" DECIMAL(65,30),
    "safety_stock_quantity" DECIMAL(65,30),
    "order_multiple" DECIMAL(65,30),
    "safety_lead_time" VARCHAR(32),
    "sales_unit_of_measure" TEXT,
    "purch_unit_of_measure" TEXT,
    "reordering_policy" INTEGER,
    "include_inventory" BOOLEAN,
    "manufacturer_code" TEXT,
    "item_category_code" TEXT,
    "product_group_code" TEXT,
    "phys_invt_counting_period_code" TEXT,
    "last_counting_period_update" TIMESTAMP(3),
    "use_cross_docking" BOOLEAN,
    "next_counting_start_date" TIMESTAMP(3),
    "next_counting_end_date" TIMESTAMP(3),
    "expiration_date_type" INTEGER,
    "expiration_date_rule" INTEGER,
    "buyer_code" TEXT,
    "crv" DECIMAL(65,30),
    "shelf_life_in_days" INTEGER,
    "shelf_life" TEXT,
    "specials_list" INTEGER,
    "sodexo_only" INTEGER,
    "pack_size" TEXT,
    "item_class" TEXT,
    "active_since" TIMESTAMP(3),
    "current_vendor_no_" TEXT,
    "commodity_dependency" INTEGER,
    "commodity_fee_basis" INTEGER,
    "fair_market_value" DECIMAL(65,30),
    "cmdy_value_exception" INTEGER,
    "df_lb_per_case" DECIMAL(65,30),
    "commodity_additional_allowance" DECIMAL(65,30),
    "onelink_order_guide" INTEGER,
    "market_price_item" BOOLEAN,
    "zero_price_allowed" BOOLEAN,
    "zone" TEXT,
    "repack_item_no_" TEXT,
    "repack_qty" DECIMAL(65,30),
    "lb_item_no_" TEXT,
    "master_item_no_" TEXT,
    "master_item" BOOLEAN,
    "njpa" BOOLEAN,
    "always_create_pick" BOOLEAN,
    "status" TEXT,
    "rebate_vendor_no_" TEXT,
    "catch_weight" BOOLEAN,
    "use_unit_of_measure_dimensions" BOOLEAN,
    "producer_of_good_indicator" INTEGER,
    "item_upc_ean_number" TEXT,
    "routing_no_" TEXT,
    "production_bom_no_" TEXT,
    "order_tracking_policy" INTEGER,
    "critical" BOOLEAN,
    "suggested_weeks_on_hand" DECIMAL(65,30),
    "city_state_zip_code_of_origin" TEXT,
    "category_class_code" TEXT,
    "gtin" TEXT,
    "mfg_name" TEXT,
    "non_domestic" BOOLEAN,
    "food_item" BOOLEAN,
    "last_direct_lb_cost" DECIMAL(65,30),
    "exception_type" TEXT,
    "_prisma_id" SERIAL NOT NULL,

    CONSTRAINT "item_history_pkey" PRIMARY KEY ("_prisma_id")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_old" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "no_2" TEXT,
    "description" TEXT,
    "description_2" TEXT,
    "base_unit_of_measure" TEXT,
    "price_unit_conversion" INTEGER,
    "type" INTEGER,
    "inventory_posting_group" TEXT,
    "item_disc_group" TEXT,
    "allow_invoice_disc" BOOLEAN,
    "unit_price" DECIMAL(65,30),
    "price_profit_calculation" INTEGER,
    "profit" DECIMAL(65,30),
    "costing_method" INTEGER,
    "unit_cost" DECIMAL(65,30),
    "last_direct_cost" DECIMAL(65,30),
    "cost_is_adjusted" BOOLEAN,
    "allow_online_adjustment" BOOLEAN,
    "vendor_no_" TEXT,
    "vendor_item_no_" TEXT,
    "lead_time_calculation" VARCHAR(32),
    "reorder_point" DECIMAL(65,30),
    "maximum_inventory" DECIMAL(65,30),
    "reorder_quantity" DECIMAL(65,30),
    "alternative_item_no_" TEXT,
    "unit_list_price" DECIMAL(65,30),
    "gross_weight" DECIMAL(65,30),
    "net_weight" DECIMAL(65,30),
    "units_per_parcel" DECIMAL(65,30),
    "unit_volume" DECIMAL(65,30),
    "country_region_purchased_code" TEXT,
    "blocked" BOOLEAN,
    "block_reason" TEXT,
    "gen_prod_posting_group" TEXT,
    "country_region_of_origin_code" TEXT,
    "reserve" INTEGER,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "lot_size" DECIMAL(65,30),
    "last_unit_cost_calc_date" TIMESTAMP(3),
    "minimum_order_quantity" DECIMAL(65,30),
    "safety_stock_quantity" DECIMAL(65,30),
    "order_multiple" DECIMAL(65,30),
    "safety_lead_time" VARCHAR(32),
    "sales_unit_of_measure" TEXT,
    "purch_unit_of_measure" TEXT,
    "reordering_policy" INTEGER,
    "include_inventory" BOOLEAN,
    "manufacturer_code" TEXT,
    "item_category_code" TEXT,
    "product_group_code" TEXT,
    "phys_invt_counting_period_code" TEXT,
    "last_counting_period_update" TIMESTAMP(3),
    "use_cross_docking" BOOLEAN,
    "next_counting_start_date" TIMESTAMP(3),
    "next_counting_end_date" TIMESTAMP(3),
    "expiration_date_type" INTEGER,
    "expiration_date_rule" INTEGER,
    "buyer_code" TEXT,
    "crv" DECIMAL(65,30),
    "shelf_life_in_days" INTEGER,
    "shelf_life" TEXT,
    "specials_list" INTEGER,
    "sodexo_only" INTEGER,
    "pack_size" TEXT,
    "item_class" TEXT,
    "active_since" TIMESTAMP(3),
    "current_vendor_no_" TEXT,
    "commodity_dependency" INTEGER,
    "commodity_fee_basis" INTEGER,
    "fair_market_value" DECIMAL(65,30),
    "cmdy_value_exception" INTEGER,
    "df_lb_per_case" DECIMAL(65,30),
    "commodity_additional_allowance" DECIMAL(65,30),
    "onelink_order_guide" INTEGER,
    "market_price_item" BOOLEAN,
    "zero_price_allowed" BOOLEAN,
    "zone" TEXT,
    "repack_item_no_" TEXT,
    "repack_qty" DECIMAL(65,30),
    "lb_item_no_" TEXT,
    "master_item_no_" TEXT,
    "master_item" BOOLEAN,
    "njpa" BOOLEAN,
    "always_create_pick" BOOLEAN,
    "status" TEXT,
    "rebate_vendor_no_" TEXT,
    "catch_weight" BOOLEAN,
    "use_unit_of_measure_dimensions" BOOLEAN,
    "producer_of_good_indicator" INTEGER,
    "item_upc_ean_number" TEXT,
    "routing_no_" TEXT,
    "production_bom_no_" TEXT,
    "order_tracking_policy" INTEGER,
    "critical" BOOLEAN,
    "suggested_weeks_on_hand" DECIMAL(65,30),
    "city_state_zip_code_of_origin" TEXT,
    "category_class_code" TEXT,
    "gtin" TEXT,
    "mfg_name" TEXT,
    "non_domestic" BOOLEAN,

    CONSTRAINT "item_old_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_spec" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "item_no_" TEXT NOT NULL,
    "jan" BOOLEAN,
    "feb" BOOLEAN,
    "mar" BOOLEAN,
    "apr" BOOLEAN,
    "may" BOOLEAN,
    "jun" BOOLEAN,
    "jul" BOOLEAN,
    "aug" BOOLEAN,
    "sep" BOOLEAN,
    "oct" BOOLEAN,
    "nov" BOOLEAN,
    "dec" BOOLEAN,
    "sb12" INTEGER,
    "sb965" INTEGER,
    "sb80" INTEGER,
    "smart_snack" BOOLEAN,
    "hhka_non_compliant" INTEGER,
    "alliance_healthgen" INTEGER,
    "california_fresh_meal_program" INTEGER,
    "egg" INTEGER,
    "soy" INTEGER,
    "milk" INTEGER,
    "wheat" INTEGER,
    "whey" INTEGER,
    "peanut" INTEGER,
    "kosher" BOOLEAN,
    "51_whole_grain" INTEGER,
    "highfructosecornsfree" INTEGER,
    "reduced_sodium" INTEGER,
    "gluten_free" INTEGER,
    "organic" BOOLEAN,
    "biodegradable" INTEGER,
    "vegetarian" BOOLEAN,
    "contains_peanut" INTEGER,
    "recycled_materials" INTEGER,
    "contains_lftp_pink_slime" INTEGER,
    "cn_contributions_breads" DECIMAL(65,30),
    "cn_contributions_meat" DECIMAL(65,30),
    "cn_contributions_fruit" DECIMAL(65,30),
    "cn_contributions_vegetable" DECIMAL(65,30),
    "cn_contributions" TEXT,
    "component_risk" INTEGER,
    "repack_item_no_" TEXT,
    "repack_qty" DECIMAL(65,30),
    "lb_item_no_" TEXT,
    "master_item_no_" TEXT,
    "master_item" BOOLEAN,
    "servings_per_case" TEXT,
    "peanut_free_facility" INTEGER,
    "cn_labeled" INTEGER,
    "vegan" BOOLEAN,
    "serving_size" TEXT,
    "units_per_serving" TEXT,
    "pack_quantity" TEXT,
    "hardy_produce" INTEGER,
    "processed_produce" INTEGER,
    "local_food_for_schools_program" INTEGER,
    "brominated_vegetable_oil" INTEGER,
    "potassium_bromates" INTEGER,
    "propylparaben" INTEGER,
    "red_dye_3" INTEGER,
    "sf_best_practices_program" INTEGER,
    "sca_program" INTEGER,

    CONSTRAINT "item_spec_pkey" PRIMARY KEY ("source_db","item_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_unit_of_measure" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "item_no_" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "length" DECIMAL(65,30),
    "width" DECIMAL(65,30),
    "height" DECIMAL(65,30),
    "cubage" DECIMAL(65,30),
    "weight" DECIMAL(65,30),
    "std_pack_upc_ean_number" TEXT,
    "max_adjust_qty" DECIMAL(65,30),
    "sync_filter" TEXT,

    CONSTRAINT "item_unit_of_measure_pkey" PRIMARY KEY ("source_db","item_no_","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_charge" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "description" TEXT,
    "gen_prod_posting_group" TEXT,
    "tax_group_code" TEXT,
    "vat_prod_posting_group" TEXT,
    "search_description" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,

    CONSTRAINT "item_charge_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_date_range" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "item_no_" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "starting_date" TIMESTAMP(3) NOT NULL,
    "ending_date" TIMESTAMP(3),
    "quantity" DECIMAL(65,30),
    "amount" DECIMAL(65,30),
    "text" TEXT,

    CONSTRAINT "item_date_range_pkey" PRIMARY KEY ("source_db","item_no_","code","starting_date")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_grouping" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "type" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "item_type" INTEGER NOT NULL,
    "item_code" TEXT NOT NULL,
    "exclude" BOOLEAN,

    CONSTRAINT "item_grouping_pkey" PRIMARY KEY ("source_db","type","code","item_type","item_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."customer" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "name" TEXT,
    "name_2" TEXT,
    "address" TEXT,
    "address_2" TEXT,
    "city" TEXT,
    "contact" TEXT,
    "phone_no_" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "customer_posting_group" TEXT,
    "payment_terms_code" TEXT,
    "salesperson_code" TEXT,
    "shipment_method_code" TEXT,
    "invoice_disc_code" TEXT,
    "customer_disc_group" TEXT,
    "country_region_code" TEXT,
    "print_statements" BOOLEAN,
    "bill_to_customer_no_" TEXT,
    "payment_method_code" TEXT,
    "location_code" TEXT,
    "combine_shipments" BOOLEAN,
    "gen_bus_posting_group" TEXT,
    "post_code" TEXT,
    "county" TEXT,
    "e_mail" TEXT,
    "tax_area_code" TEXT,
    "tax_liable" BOOLEAN,
    "reserve" INTEGER,
    "primary_contact_no_" TEXT,
    "allow_line_disc" BOOLEAN,
    "tax_area_id" TEXT,
    "csr" TEXT,
    "district_group_code" TEXT,
    "price_orders_at_shipment" BOOLEAN,
    "geographic_code" TEXT,
    "sodexo_unit_no_" TEXT,
    "ra_no_" TEXT,
    "hours_of_operation" TEXT,
    "bill_to_primary_contact_no_" TEXT,
    "default_external_document_no_" TEXT,
    "dod_usda_customer_no_" TEXT,
    "allow_zero_qty_lines" BOOLEAN,
    "combine_bread_broadline" BOOLEAN,
    "online_customer" BOOLEAN,
    "pricing_uses_order_date" INTEGER,
    "charge_storage_fees" INTEGER,
    "rebate_invoices" BOOLEAN,
    "ups_location_code" TEXT,
    "exclude_from_crv" BOOLEAN,
    "use_invoice_with_zones" BOOLEAN,
    "special_instructions" TEXT,
    "bill_to_customer" INTEGER,
    "customer_accepts_subs" INTEGER,
    "keys_to_gate" INTEGER,
    "keys_to_kitchen" INTEGER,
    "keys_to_walk_in" INTEGER,
    "co_op_code" TEXT,
    "5_star_exception" INTEGER,
    "do_not_combine" BOOLEAN,
    "do_not_break_item" INTEGER,
    "tls" INTEGER,
    "order_type" TEXT,
    "njpa_code" INTEGER,
    "customer_drop_type" TEXT,
    "pallet_per_item" INTEGER,
    "audit_picks" BOOLEAN,
    "edi_invoice" INTEGER,
    "edi_trade_partner" TEXT,
    "dod_customer" BOOLEAN,
    "chain_name" TEXT,
    "priority" INTEGER,
    "legacy_no_" TEXT,
    "sync_filter" TEXT,
    "credit_limit_lcy" DECIMAL(65,30),
    "type" TEXT,
    "group" TEXT,
    "status" TEXT,
    "account_type" TEXT,
    "commodity_region" TEXT,

    CONSTRAINT "customer_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."customer_grouping" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "type" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "customer_type" INTEGER NOT NULL,
    "customer_code" TEXT NOT NULL,
    "priority" INTEGER,
    "exclude" BOOLEAN,

    CONSTRAINT "customer_grouping_pkey" PRIMARY KEY ("source_db","type","code","customer_type","customer_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."contact" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "name" TEXT,
    "search_name" TEXT,
    "name_2" TEXT,
    "address" TEXT,
    "address_2" TEXT,
    "city" TEXT,
    "phone_no_" TEXT,
    "salesperson_code" TEXT,
    "fax_no_" TEXT,
    "post_code" TEXT,
    "county" TEXT,
    "e_mail" TEXT,
    "home_page" TEXT,
    "no_series" TEXT,
    "type" INTEGER,
    "company_no_" TEXT,
    "company_name" TEXT,
    "first_name" TEXT,
    "middle_name" TEXT,
    "surname" TEXT,
    "job_title" TEXT,
    "mobile_phone_no_" TEXT,
    "pager" TEXT,
    "organizational_level_code" TEXT,
    "exclude_from_segment" BOOLEAN,
    "search_e_mail" TEXT,
    "e_mail_2" TEXT,

    CONSTRAINT "contact_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."contact_business_relation" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "contact_no_" TEXT NOT NULL,
    "business_relation_code" TEXT NOT NULL,
    "link_to_table" INTEGER,
    "no_" TEXT,

    CONSTRAINT "contact_business_relation_pkey" PRIMARY KEY ("source_db","contact_no_","business_relation_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."employee" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "first_name" TEXT,
    "middle_name" TEXT,
    "last_name" TEXT,
    "initials" TEXT,
    "job_title" TEXT,
    "e_mail" TEXT,
    "manager_no_" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,

    CONSTRAINT "employee_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."location" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "code" TEXT NOT NULL,
    "name" TEXT,
    "default_bin_code" TEXT,
    "name_2" TEXT,
    "address" TEXT,
    "address_2" TEXT,
    "city" TEXT,
    "post_code" TEXT,
    "county" TEXT,
    "use_as_in_transit" BOOLEAN,
    "require_put_away" BOOLEAN,
    "require_pick" BOOLEAN,
    "cross_dock_due_date_calc" VARCHAR(32),
    "use_cross_docking" BOOLEAN,
    "require_receive" BOOLEAN,
    "require_shipment" BOOLEAN,
    "bin_mandatory" INTEGER,
    "directed_put_away_and_pick" BOOLEAN,
    "default_bin_selection" INTEGER,
    "outbound_whse_handling_time" VARCHAR(32),
    "inbound_whse_handling_time" VARCHAR(32),
    "put_away_template_code" TEXT,
    "use_put_away_worksheet" BOOLEAN,
    "pick_according_to_fefo" BOOLEAN,
    "allow_breakbulk" BOOLEAN,
    "bin_capacity_policy" INTEGER,
    "open_shop_floor_bin_code" TEXT,
    "to_production_bin_code" TEXT,
    "from_production_bin_code" TEXT,
    "adjustment_bin_code" TEXT,
    "always_create_put_away_line" BOOLEAN,
    "always_create_pick_line" BOOLEAN,
    "receipt_bin_code" TEXT,
    "shipment_bin_code" TEXT,
    "cross_dock_bin_code" TEXT,
    "license_plate_lot_tracking" INTEGER,
    "pick_from_total_available_qty" BOOLEAN,
    "use_gsf_epiration_for_replen" BOOLEAN,
    "purchase_label_code" TEXT,
    "argent_output_folder" TEXT,
    "print_pallet_counter" INTEGER,
    "pallet_label_code" TEXT,
    "general_pk" TEXT,
    "bulk_pick" DECIMAL(65,30),
    "position_cost" INTEGER,
    "aisle_side_cost" INTEGER,
    "height_cost" INTEGER,
    "change_aisle_cost" INTEGER,
    "no_of_aisles_to_search" INTEGER,
    "xml_export_path" TEXT,
    "update_pick_logic" INTEGER,
    "route_closing_action" INTEGER,
    "asc_order_lock_enabled" BOOLEAN,
    "pallet_replenishment" INTEGER,
    "ignore_min_qty_in_replenish" INTEGER,
    "print_auto_put_away" BOOLEAN,
    "xml_printers" INTEGER,
    "last_xml_printer_number" INTEGER,
    "route_label_stylesheet" TEXT,
    "batch_label_stylesheet" TEXT,
    "batch_summary_label_stylesheet" TEXT,
    "aisle_warning_label_stylesheet" TEXT,
    "bulk_pick_label_stylesheet" TEXT,
    "bulk_pick_return_stylesheet" TEXT,
    "item_label_stylesheet" TEXT,
    "catch_weight_label_stylesheet" TEXT,
    "pallet_label_stylesheet" TEXT,
    "unique_label_nos" TEXT,
    "pallet_layer_height" DECIMAL(65,30),
    "wait_period_rec_worksh_mins" INTEGER,
    "aisle_code_length" INTEGER,
    "pass_counter" INTEGER,
    "no_fixed_bin_setup_code" TEXT,
    "receive_label_format" TEXT,
    "receive_label_jobname" TEXT,
    "receive_label_printnumber" INTEGER,
    "receive_label_quantity" INTEGER,
    "po_label_format" TEXT,
    "po_label_jobname" TEXT,
    "po_label_printnumber" INTEGER,
    "po_label_quantity" INTEGER,
    "allow_empty_at_split_pallet" BOOLEAN,
    "repack_item_jnl_template" TEXT,
    "repack_item_jnl_batch" TEXT,
    "show_replen_worksheet" BOOLEAN,
    "show_preview_for_bread_report" BOOLEAN,
    "show_nav_receipt_posting_error" BOOLEAN,
    "do_not_print_purchase_labels" BOOLEAN,
    "do_not_print_pick_labels" BOOLEAN,
    "put_away_test_mode" BOOLEAN,
    "whse_rcpt_per_pallet" INTEGER,
    "use_assumed_receipt" BOOLEAN,
    "replenishment_source_bin_type" TEXT,
    "bread_bin" TEXT,
    "qa_hold_code" TEXT,
    "no_pick_bin_code_picking" TEXT,
    "create_dummy_pick_bin_setup" BOOLEAN,
    "delete_emplty_batch_labels" INTEGER,
    "default_dimension" TEXT,
    "max_bin_nearby_check" INTEGER,
    "physical_inventory_manager" TEXT,
    "max_labels_for_item" INTEGER,
    "pick_from_reserve" INTEGER,
    "invoice_printer" TEXT,
    "use_locking" BOOLEAN,
    "registering_user" TEXT,
    "invoicing_user" TEXT,
    "picking_user" TEXT,
    "po_close_email" TEXT,
    "allow_negative_bin_inventory" BOOLEAN,
    "print_metric_data" BOOLEAN,
    "bulk_label_qty" INTEGER,
    "show_label_metric_data" BOOLEAN,
    "residential_delivery" BOOLEAN,
    "shipping_payment_type" INTEGER,
    "initial_lp_qa_status" TEXT,
    "create_lp_pallets_at_receive" BOOLEAN,
    "use_license_plating" BOOLEAN,
    "pallet_adjustment_bin" TEXT,
    "require_pallet_qa_record" INTEGER,
    "use_fifo_pick_takes_lp" BOOLEAN,
    "use_fifo_replen_takes_lp" BOOLEAN,
    "strict_pallet_bins" INTEGER,
    "allow_picking_from_lp" BOOLEAN,
    "enter_catch_weight" BOOLEAN,

    CONSTRAINT "location_pkey" PRIMARY KEY ("source_db","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."bank_account" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "name" TEXT,
    "search_name" TEXT,
    "name_2" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "bank_acc_posting_group" TEXT,
    "last_check_no_" TEXT,

    CONSTRAINT "bank_account_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."fixed_asset" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "description" TEXT,
    "search_description" TEXT,
    "description_2" TEXT,
    "fa_class_code" TEXT,
    "fa_subclass_code" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "location_code" TEXT,
    "fa_location_code" TEXT,
    "vendor_no_" TEXT,
    "responsible_employee" TEXT,
    "serial_no_" TEXT,
    "blocked" BOOLEAN,
    "maintenance_vendor_no_" TEXT,
    "under_maintenance" INTEGER,
    "inactive" BOOLEAN,
    "no_series" TEXT,
    "fa_posting_group" TEXT,

    CONSTRAINT "fixed_asset_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."g_l_account" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "name" TEXT,
    "search_name" TEXT,
    "account_type" INTEGER,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "account_category" INTEGER,
    "income_balance" INTEGER,
    "debit_credit" INTEGER,
    "no_2" TEXT,
    "blocked" BOOLEAN,
    "direct_posting" INTEGER,
    "reconciliation_account" INTEGER,
    "gen_posting_type" INTEGER,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "tax_area_code" TEXT,
    "tax_liable" BOOLEAN,
    "tax_group_code" TEXT,
    "id" TEXT,

    CONSTRAINT "g_l_account_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."g_l_entry" (
    "source_db" TEXT NOT NULL,
    "entry_no_" INTEGER NOT NULL,
    "g_l_account_no_" TEXT,
    "posting_date" TIMESTAMP(3),
    "document_type" INTEGER,
    "document_no_" TEXT,
    "description" TEXT,
    "bal_account_no_" TEXT,
    "amount" DECIMAL(65,30),
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "user_id" TEXT,
    "source_code" TEXT,
    "quantity" DECIMAL(65,30),
    "journal_batch_name" TEXT,
    "reason_code" TEXT,
    "gen_posting_type" INTEGER,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "transaction_no_" INTEGER,
    "debit_amount" DECIMAL(65,30),
    "credit_amount" DECIMAL(65,30),
    "document_date" TIMESTAMP(3),
    "source_type" INTEGER,
    "source_no_" TEXT,
    "no_series" TEXT,
    "dimension_set_id" INTEGER,
    "external_document_no_" TEXT,

    CONSTRAINT "g_l_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."cust_ledger_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "customer_no_" TEXT,
    "posting_date" TIMESTAMP(3),
    "document_type" INTEGER,
    "document_no_" TEXT,
    "description" TEXT,
    "sales_lcy" DECIMAL(65,30),
    "profit_lcy" DECIMAL(65,30),
    "inv_discount_lcy" DECIMAL(65,30),
    "sell_to_customer_no_" TEXT,
    "customer_posting_group" TEXT,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "salesperson_code" TEXT,
    "user_id" TEXT,
    "source_code" TEXT,
    "open" BOOLEAN,
    "due_date" TIMESTAMP(3),
    "pmt_discount_date" TIMESTAMP(3),
    "original_pmt_disc_possible" DECIMAL(65,30),
    "pmt_disc_given_lcy" DECIMAL(65,30),
    "positive" BOOLEAN,
    "closed_by_entry_no_" INTEGER,
    "closed_at_date" TIMESTAMP(3),
    "closed_by_amount" DECIMAL(65,30),
    "applies_to_id" TEXT,
    "journal_batch_name" TEXT,
    "reason_code" TEXT,
    "bal_account_type" INTEGER,
    "bal_account_no_" TEXT,
    "transaction_no_" INTEGER,
    "closed_by_amount_lcy" DECIMAL(65,30),
    "document_date" TIMESTAMP(3),
    "external_document_no_" TEXT,
    "no_series" TEXT,
    "closed_by_currency_amount" DECIMAL(65,30),
    "adjusted_currency_factor" DECIMAL(65,30),
    "original_currency_factor" DECIMAL(65,30),
    "remaining_pmt_disc_possible" DECIMAL(65,30),
    "pmt_disc_tolerance_date" TIMESTAMP(3),
    "dimension_set_id" INTEGER,
    "order_type" TEXT,

    CONSTRAINT "cust_ledger_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."detailed_cust_ledg_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "cust_ledger_entry_no_" INTEGER,
    "entry_type" INTEGER,
    "posting_date" TIMESTAMP(3),
    "document_type" INTEGER,
    "document_no_" TEXT,
    "amount" DECIMAL(65,30),
    "amount_lcy" DECIMAL(65,30),
    "customer_no_" TEXT,
    "user_id" TEXT,
    "source_code" TEXT,
    "transaction_no_" INTEGER,
    "journal_batch_name" TEXT,
    "reason_code" TEXT,
    "debit_amount" DECIMAL(65,30),
    "credit_amount" DECIMAL(65,30),
    "debit_amount_lcy" DECIMAL(65,30),
    "credit_amount_lcy" DECIMAL(65,30),
    "initial_entry_due_date" TIMESTAMP(3),
    "initial_entry_global_dim_1" TEXT,
    "initial_entry_global_dim_2" TEXT,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "initial_document_type" INTEGER,
    "applied_cust_ledger_entry_no_" INTEGER,
    "unapplied" BOOLEAN,
    "unapplied_by_entry_no_" INTEGER,
    "remaining_pmt_disc_possible" DECIMAL(65,30),
    "max_payment_tolerance" DECIMAL(65,30),
    "ledger_entry_amount" BOOLEAN,

    CONSTRAINT "detailed_cust_ledg_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."detailed_vendor_ledg_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "vendor_ledger_entry_no_" INTEGER,
    "entry_type" INTEGER,
    "posting_date" TIMESTAMP(3),
    "document_type" INTEGER,
    "document_no_" TEXT,
    "amount" DECIMAL(65,30),
    "amount_lcy" DECIMAL(65,30),
    "vendor_no_" TEXT,
    "user_id" TEXT,
    "source_code" TEXT,
    "transaction_no_" INTEGER,
    "journal_batch_name" TEXT,
    "reason_code" TEXT,
    "debit_amount" DECIMAL(65,30),
    "credit_amount" DECIMAL(65,30),
    "debit_amount_lcy" DECIMAL(65,30),
    "credit_amount_lcy" DECIMAL(65,30),
    "initial_entry_due_date" TIMESTAMP(3),
    "initial_entry_global_dim_1" TEXT,
    "initial_entry_global_dim_2" TEXT,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "initial_document_type" INTEGER,
    "applied_vend_ledger_entry_no_" INTEGER,
    "unapplied" BOOLEAN,
    "unapplied_by_entry_no_" INTEGER,
    "remaining_pmt_disc_possible" DECIMAL(65,30),
    "max_payment_tolerance" DECIMAL(65,30),
    "tax_jurisdiction_code" TEXT,
    "application_no_" INTEGER,
    "ledger_entry_amount" BOOLEAN,

    CONSTRAINT "detailed_vendor_ledg_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_ledger_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "item_no_" TEXT,
    "posting_date" TIMESTAMP(3),
    "entry_type" INTEGER,
    "source_no_" TEXT,
    "document_no_" TEXT,
    "description" TEXT,
    "location_code" TEXT,
    "quantity" DECIMAL(65,30),
    "remaining_quantity" DECIMAL(65,30),
    "invoiced_quantity" DECIMAL(65,30),
    "applies_to_entry" INTEGER,
    "open" BOOLEAN,
    "global_dimension_1_code" TEXT,
    "global_dimension_2_code" TEXT,
    "positive" BOOLEAN,
    "source_type" INTEGER,
    "drop_shipment" BOOLEAN,
    "country_region_code" TEXT,
    "document_date" TIMESTAMP(3),
    "external_document_no_" TEXT,
    "no_series" TEXT,
    "document_type" INTEGER,
    "document_line_no_" INTEGER,
    "order_type" INTEGER,
    "order_no_" TEXT,
    "order_line_no_" INTEGER,
    "dimension_set_id" INTEGER,
    "assemble_to_order" BOOLEAN,
    "variant_code" TEXT,
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "unit_of_measure_code" TEXT,
    "item_category_code" TEXT,
    "product_group_code" TEXT,
    "completely_invoiced" BOOLEAN,
    "last_invoice_date" TIMESTAMP(3),
    "correction" BOOLEAN,
    "shipped_qty_not_returned" DECIMAL(65,30),
    "lot_no_" TEXT,
    "expiration_date" TIMESTAMP(3),
    "item_tracking" INTEGER,
    "return_reason_code" TEXT,
    "bill_to_customer_no_" TEXT,
    "reason_code" TEXT,
    "true_posting_date_time" TIMESTAMP(3),

    CONSTRAINT "item_ledger_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."item_application_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "item_ledger_entry_no_" INTEGER,
    "inbound_item_entry_no_" INTEGER,
    "outbound_item_entry_no_" INTEGER,
    "quantity" DECIMAL(65,30),
    "posting_date" TIMESTAMP(3),
    "transferred_from_entry_no_" INTEGER,
    "creation_date" TIMESTAMP(3),
    "created_by_user" TEXT,
    "last_modified_date" TIMESTAMP(3),
    "last_modified_by_user" TEXT,
    "cost_application" INTEGER,
    "output_completely_invd_date" TIMESTAMP(3),
    "outbound_entry_is_updated" BOOLEAN,

    CONSTRAINT "item_application_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."commodity_ledger_entry" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "item_no_" TEXT,
    "posting_date" TIMESTAMP(3),
    "entry_type" INTEGER,
    "document_no_" TEXT,
    "vendor_group_code" TEXT,
    "document_type" INTEGER,
    "document_line_no_" INTEGER,
    "item_ledger_entry_no_" INTEGER,
    "true_posting_date_time" TIMESTAMP(3),
    "quantity" DECIMAL(65,30),
    "bill_to_customer_no_" TEXT,
    "distributor_name" TEXT,
    "distributor_sub_name" TEXT,
    "co_op_district_quantity_code" TEXT,
    "amount" DECIMAL(65,30),
    "fair_market_value" DECIMAL(65,30),
    "unit_of_measure_code" TEXT,
    "reason_code" TEXT,
    "gsf_item" BOOLEAN,
    "finished_good" BOOLEAN,
    "reported_by" TEXT,
    "co_op_district_amount_code" TEXT,
    "entitlement_type" TEXT,
    "outside_sale" BOOLEAN,
    "state_code" TEXT,
    "commodity_region" TEXT,

    CONSTRAINT "commodity_ledger_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."change_log_entry" (
    "source_db" TEXT NOT NULL,
    "entry_no_" BIGINT NOT NULL,
    "date_and_time" TIMESTAMP(3),
    "time" TIMESTAMP(3),
    "user_id" TEXT,
    "table_no_" INTEGER,
    "field_no_" INTEGER,
    "type_of_change" INTEGER,
    "old_value" TEXT,
    "new_value" TEXT,
    "primary_key_field_1_no_" INTEGER,
    "primary_key_field_1_value" TEXT,
    "primary_key_field_2_no_" INTEGER,
    "primary_key_field_2_value" TEXT,
    "primary_key_field_3_no_" INTEGER,
    "primary_key_field_3_value" TEXT,

    CONSTRAINT "change_log_entry_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."change_log_entry_full_history" (
    "source_db" TEXT NOT NULL,
    "entry_no_" BIGINT NOT NULL,
    "date_and_time" TIMESTAMP(3),
    "time" TIMESTAMP(3),
    "user_id" TEXT,
    "table_no_" INTEGER,
    "field_no_" INTEGER,
    "type_of_change" INTEGER,
    "old_value" TEXT,
    "new_value" TEXT,
    "primary_key_field_1_no_" INTEGER,
    "primary_key_field_1_value" TEXT,
    "primary_key_field_2_no_" INTEGER,
    "primary_key_field_2_value" TEXT,
    "primary_key_field_3_no_" INTEGER,
    "primary_key_field_3_value" TEXT,

    CONSTRAINT "change_log_entry_full_history_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purch_inv_header" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "pay_to_vendor_no_" TEXT,
    "pay_to_name" TEXT,
    "pay_to_address" TEXT,
    "pay_to_address_2" TEXT,
    "pay_to_city" TEXT,
    "pay_to_contact" TEXT,
    "your_reference" TEXT,
    "ship_to_name" TEXT,
    "ship_to_address" TEXT,
    "ship_to_address_2" TEXT,
    "ship_to_city" TEXT,
    "ship_to_contact" TEXT,
    "order_date" TIMESTAMP(3),
    "posting_date" TIMESTAMP(3),
    "expected_receipt_date" TIMESTAMP(3),
    "posting_description" TEXT,
    "payment_terms_code" TEXT,
    "due_date" TIMESTAMP(3),
    "payment_discount" DECIMAL(65,30),
    "pmt_discount_date" TIMESTAMP(3),
    "shipment_method_code" TEXT,
    "location_code" TEXT,
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "vendor_posting_group" TEXT,
    "invoice_disc_code" TEXT,
    "language_code" TEXT,
    "purchaser_code" TEXT,
    "order_no_" TEXT,
    "no_printed" INTEGER,
    "on_hold" TEXT,
    "applies_to_doc_type" INTEGER,
    "applies_to_doc_no_" TEXT,
    "bal_account_no_" TEXT,
    "vendor_order_no_" TEXT,
    "vendor_invoice_no_" TEXT,
    "vat_registration_no_" TEXT,
    "sell_to_customer_no_" TEXT,
    "gen_bus_posting_group" TEXT,
    "vat_country_region_code" TEXT,
    "buy_from_vendor_name" TEXT,
    "buy_from_address" TEXT,
    "buy_from_address_2" TEXT,
    "buy_from_city" TEXT,
    "buy_from_contact" TEXT,
    "pay_to_post_code" TEXT,
    "pay_to_county" TEXT,
    "pay_to_country_region_code" TEXT,
    "buy_from_post_code" TEXT,
    "buy_from_county" TEXT,
    "buy_from_country_region_code" TEXT,
    "ship_to_post_code" TEXT,
    "ship_to_county" TEXT,
    "ship_to_country_region_code" TEXT,
    "order_address_code" TEXT,
    "document_date" TIMESTAMP(3),
    "payment_method_code" TEXT,
    "pre_assigned_no_series" TEXT,
    "no_series" TEXT,
    "order_no_series" TEXT,
    "pre_assigned_no_" TEXT,
    "user_id" TEXT,
    "source_code" TEXT,
    "prepayment_no_series" TEXT,
    "prepayment_invoice" BOOLEAN,
    "prepayment_order_no_" TEXT,
    "dimension_set_id" INTEGER,
    "vendor_ledger_entry_no_" INTEGER,
    "buy_from_contact_no_" TEXT,
    "pay_to_contact_no_" TEXT,
    "id" TEXT,
    "irs_1099_code" TEXT,
    "storage_customer" TEXT,
    "rebate_start_date" TIMESTAMP(3),
    "rebate_end_date" TIMESTAMP(3),
    "disposition_no_" TEXT,
    "offering_no_" TEXT,
    "co_op_code" TEXT,
    "drop_ship_so_no_" TEXT,
    "edi_order" BOOLEAN,
    "edi_internal_doc_no_" TEXT,
    "edi_po_generated" BOOLEAN,
    "edi_po_gen_date" TIMESTAMP(3),
    "edi_ship_adv_gen" BOOLEAN,
    "edi_ship_adv_gen_date" TIMESTAMP(3),
    "edi_trade_partner" TEXT,
    "edi_buy_from_code" TEXT,
    "e_mail_invoice_notice_handled" BOOLEAN,
    "usda_po_no_" TEXT,

    CONSTRAINT "purch_inv_header_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purch_inv_line" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "document_no_" TEXT NOT NULL,
    "line_no_" INTEGER NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "type" INTEGER,
    "no_" TEXT,
    "location_code" TEXT,
    "posting_group" TEXT,
    "expected_receipt_date" TIMESTAMP(3),
    "description" TEXT,
    "description_2" TEXT,
    "unit_of_measure" TEXT,
    "quantity" DECIMAL(65,30),
    "direct_unit_cost" DECIMAL(65,30),
    "unit_cost_lcy" DECIMAL(65,30),
    "amount" DECIMAL(65,30),
    "amount_including_vat" DECIMAL(65,30),
    "unit_price_lcy" DECIMAL(65,30),
    "allow_invoice_disc" BOOLEAN,
    "gross_weight" DECIMAL(65,30),
    "net_weight" DECIMAL(65,30),
    "units_per_parcel" DECIMAL(65,30),
    "unit_volume" DECIMAL(65,30),
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "pay_to_vendor_no_" TEXT,
    "vendor_item_no_" TEXT,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "vat_calculation_type" INTEGER,
    "tax_group_code" TEXT,
    "vat_base_amount" DECIMAL(65,30),
    "unit_cost" DECIMAL(65,30),
    "line_amount" DECIMAL(65,30),
    "ic_partner_code" TEXT,
    "posting_date" TIMESTAMP(3),
    "dimension_set_id" INTEGER,
    "variant_code" TEXT,
    "bin_code" TEXT,
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "unit_of_measure_code" TEXT,
    "quantity_base" DECIMAL(65,30),
    "item_category_code" TEXT,
    "product_group_code" TEXT,
    "irs_1099_liable" INTEGER,
    "cmdty_value_per_lb" DECIMAL(65,30),
    "pounds" DECIMAL(65,30),
    "cost_per_pound" DECIMAL(65,30),
    "shipping_charge" BOOLEAN,
    "over_receive" BOOLEAN,
    "over_receive_verified" BOOLEAN,
    "routing_no_" TEXT,
    "operation_no_" TEXT,
    "work_center_no_" TEXT,
    "prod_order_line_no_" INTEGER,
    "overhead_rate" DECIMAL(65,30),
    "routing_reference_no_" INTEGER,
    "appl_to_order_no_" TEXT,

    CONSTRAINT "purch_inv_line_pkey" PRIMARY KEY ("source_db","document_no_","line_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purch_rcpt_header" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "pay_to_vendor_no_" TEXT,
    "pay_to_name" TEXT,
    "pay_to_name_2" TEXT,
    "pay_to_address" TEXT,
    "pay_to_address_2" TEXT,
    "pay_to_city" TEXT,
    "pay_to_contact" TEXT,
    "your_reference" TEXT,
    "ship_to_code" TEXT,
    "ship_to_name" TEXT,
    "ship_to_name_2" TEXT,
    "ship_to_address" TEXT,
    "ship_to_address_2" TEXT,
    "ship_to_city" TEXT,
    "ship_to_contact" TEXT,
    "order_date" TIMESTAMP(3),
    "posting_date" TIMESTAMP(3),
    "expected_receipt_date" TIMESTAMP(3),
    "posting_description" TEXT,
    "payment_terms_code" TEXT,
    "due_date" TIMESTAMP(3),
    "payment_discount" DECIMAL(65,30),
    "pmt_discount_date" TIMESTAMP(3),
    "shipment_method_code" TEXT,
    "location_code" TEXT,
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "vendor_posting_group" TEXT,
    "invoice_disc_code" TEXT,
    "purchaser_code" TEXT,
    "order_no_" TEXT,
    "vendor_order_no_" TEXT,
    "vendor_shipment_no_" TEXT,
    "sell_to_customer_no_" TEXT,
    "reason_code" TEXT,
    "gen_bus_posting_group" TEXT,
    "vat_country_region_code" TEXT,
    "buy_from_vendor_name" TEXT,
    "buy_from_vendor_name_2" TEXT,
    "buy_from_address" TEXT,
    "buy_from_address_2" TEXT,
    "buy_from_city" TEXT,
    "buy_from_contact" TEXT,
    "pay_to_post_code" TEXT,
    "pay_to_county" TEXT,
    "pay_to_country_region_code" TEXT,
    "buy_from_post_code" TEXT,
    "buy_from_county" TEXT,
    "buy_from_country_region_code" TEXT,
    "ship_to_post_code" TEXT,
    "ship_to_county" TEXT,
    "ship_to_country_region_code" TEXT,
    "correction" BOOLEAN,
    "document_date" TIMESTAMP(3),
    "payment_method_code" TEXT,
    "no_series" TEXT,
    "order_no_series" TEXT,
    "user_id" TEXT,
    "source_code" TEXT,
    "dimension_set_id" INTEGER,
    "buy_from_contact_no_" TEXT,
    "pay_to_contact_no_" TEXT,
    "lead_time_calculation" VARCHAR(32),
    "disposition_no_" TEXT,
    "offering_no_" TEXT,
    "co_op_code" TEXT,
    "freight_vendor" TEXT,
    "freight_amount" DECIMAL(65,30),

    CONSTRAINT "purch_rcpt_header_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purch_rcpt_line" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "document_no_" TEXT NOT NULL,
    "line_no_" INTEGER NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "type" INTEGER,
    "no_" TEXT,
    "location_code" TEXT,
    "posting_group" TEXT,
    "expected_receipt_date" TIMESTAMP(3),
    "description" TEXT,
    "description_2" TEXT,
    "unit_of_measure" TEXT,
    "quantity" DECIMAL(65,30),
    "direct_unit_cost" DECIMAL(65,30),
    "unit_cost_lcy" DECIMAL(65,30),
    "line_discount" DECIMAL(65,30),
    "unit_price_lcy" DECIMAL(65,30),
    "allow_invoice_disc" BOOLEAN,
    "gross_weight" DECIMAL(65,30),
    "net_weight" DECIMAL(65,30),
    "units_per_parcel" DECIMAL(65,30),
    "unit_volume" DECIMAL(65,30),
    "appl_to_item_entry" INTEGER,
    "item_rcpt_entry_no_" INTEGER,
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "indirect_cost" DECIMAL(65,30),
    "qty_rcd_not_invoiced" DECIMAL(65,30),
    "quantity_invoiced" DECIMAL(65,30),
    "order_no_" TEXT,
    "order_line_no_" INTEGER,
    "pay_to_vendor_no_" TEXT,
    "vendor_item_no_" TEXT,
    "sales_order_no_" TEXT,
    "sales_order_line_no_" INTEGER,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "vat_calculation_type" INTEGER,
    "unit_cost" DECIMAL(65,30),
    "posting_date" TIMESTAMP(3),
    "dimension_set_id" INTEGER,
    "prod_order_no_" TEXT,
    "variant_code" TEXT,
    "bin_code" TEXT,
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "unit_of_measure_code" TEXT,
    "quantity_base" DECIMAL(65,30),
    "qty_invoiced_base" DECIMAL(65,30),
    "item_category_code" TEXT,
    "nonstock" BOOLEAN,
    "purchasing_code" TEXT,
    "product_group_code" TEXT,
    "special_order_sales_no_" TEXT,
    "special_order_sales_line_no_" INTEGER,
    "requested_receipt_date" TIMESTAMP(3),
    "promised_receipt_date" TIMESTAMP(3),
    "lead_time_calculation" VARCHAR(32),
    "inbound_whse_handling_time" VARCHAR(32),
    "planned_receipt_date" TIMESTAMP(3),
    "order_date" TIMESTAMP(3),
    "item_charge_base_amount" DECIMAL(65,30),
    "correction" BOOLEAN,
    "return_reason_code" TEXT,
    "cmdty_value_per_lb" DECIMAL(65,30),
    "pounds" DECIMAL(65,30),
    "cost_per_pound" DECIMAL(65,30),
    "shipping_charge" BOOLEAN,
    "over_receive" BOOLEAN,
    "over_receive_verified" BOOLEAN,
    "routing_no_" TEXT,
    "overhead_rate" DECIMAL(65,30),
    "routing_reference_no_" INTEGER,
    "city_state_zip_code_of_origin" TEXT,

    CONSTRAINT "purch_rcpt_line_pkey" PRIMARY KEY ("source_db","document_no_","line_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purch_cr_memo_hdr" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "no_" TEXT NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "pay_to_vendor_no_" TEXT,
    "pay_to_name" TEXT,
    "pay_to_name_2" TEXT,
    "pay_to_address" TEXT,
    "pay_to_address_2" TEXT,
    "pay_to_city" TEXT,
    "pay_to_contact" TEXT,
    "ship_to_code" TEXT,
    "ship_to_name" TEXT,
    "ship_to_name_2" TEXT,
    "ship_to_address" TEXT,
    "ship_to_address_2" TEXT,
    "ship_to_city" TEXT,
    "ship_to_contact" TEXT,
    "posting_date" TIMESTAMP(3),
    "expected_receipt_date" TIMESTAMP(3),
    "posting_description" TEXT,
    "payment_terms_code" TEXT,
    "due_date" TIMESTAMP(3),
    "shipment_method_code" TEXT,
    "location_code" TEXT,
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "vendor_posting_group" TEXT,
    "currency_code" TEXT,
    "currency_factor" DECIMAL(65,30),
    "prices_including_vat" BOOLEAN,
    "invoice_disc_code" TEXT,
    "purchaser_code" TEXT,
    "no_printed" INTEGER,
    "on_hold" TEXT,
    "applies_to_doc_type" INTEGER,
    "applies_to_doc_no_" TEXT,
    "bal_account_no_" TEXT,
    "vendor_cr_memo_no_" TEXT,
    "sell_to_customer_no_" TEXT,
    "reason_code" TEXT,
    "gen_bus_posting_group" TEXT,
    "transaction_type" TEXT,
    "transport_method" TEXT,
    "buy_from_vendor_name" TEXT,
    "buy_from_vendor_name_2" TEXT,
    "buy_from_address" TEXT,
    "buy_from_address_2" TEXT,
    "buy_from_city" TEXT,
    "buy_from_contact" TEXT,
    "pay_to_post_code" TEXT,
    "pay_to_county" TEXT,
    "pay_to_country_region_code" TEXT,
    "buy_from_post_code" TEXT,
    "buy_from_county" TEXT,
    "buy_from_country_region_code" TEXT,
    "ship_to_post_code" TEXT,
    "ship_to_county" TEXT,
    "ship_to_country_region_code" TEXT,
    "payment_method_code" TEXT,
    "source_code" TEXT,
    "dimension_set_id" INTEGER,
    "vendor_ledger_entry_no_" INTEGER,
    "rebate_type" INTEGER,
    "rebate_start_date" TIMESTAMP(3),
    "rebate_end_date" TIMESTAMP(3),
    "rebate_doc_handling" INTEGER,
    "co_op_code" TEXT,

    CONSTRAINT "purch_cr_memo_hdr_pkey" PRIMARY KEY ("source_db","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purch_cr_memo_line" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "document_no_" TEXT NOT NULL,
    "line_no_" INTEGER NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "type" INTEGER,
    "no_" TEXT,
    "location_code" TEXT,
    "posting_group" TEXT,
    "expected_receipt_date" TIMESTAMP(3),
    "description" TEXT,
    "description_2" TEXT,
    "unit_of_measure" TEXT,
    "quantity" DECIMAL(65,30),
    "direct_unit_cost" DECIMAL(65,30),
    "unit_cost_lcy" DECIMAL(65,30),
    "vat" DECIMAL(65,30),
    "line_discount" DECIMAL(65,30),
    "line_discount_amount" DECIMAL(65,30),
    "amount" DECIMAL(65,30),
    "amount_including_vat" DECIMAL(65,30),
    "unit_price_lcy" DECIMAL(65,30),
    "allow_invoice_disc" BOOLEAN,
    "gross_weight" DECIMAL(65,30),
    "net_weight" DECIMAL(65,30),
    "units_per_parcel" DECIMAL(65,30),
    "unit_volume" DECIMAL(65,30),
    "appl_to_item_entry" INTEGER,
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "pay_to_vendor_no_" TEXT,
    "inv_discount_amount" DECIMAL(65,30),
    "vendor_item_no_" TEXT,
    "gen_bus_posting_group" TEXT,
    "gen_prod_posting_group" TEXT,
    "transaction_type" TEXT,
    "tax_area_code" TEXT,
    "tax_liable" BOOLEAN,
    "tax_group_code" TEXT,
    "unit_cost" DECIMAL(65,30),
    "line_amount" DECIMAL(65,30),
    "posting_date" TIMESTAMP(3),
    "dimension_set_id" INTEGER,
    "variant_code" TEXT,
    "bin_code" TEXT,
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "unit_of_measure_code" TEXT,
    "quantity_base" DECIMAL(65,30),
    "item_category_code" TEXT,
    "nonstock" BOOLEAN,
    "purchasing_code" TEXT,
    "product_group_code" TEXT,
    "rebate_type" INTEGER,
    "rebate_source_doc_type" INTEGER,
    "rebate_source_doc_no_" TEXT,
    "rebate_source_doc_line_no_" INTEGER,
    "cmdty_value_per_lb" DECIMAL(65,30),
    "pounds" DECIMAL(65,30),
    "cost_per_pound" DECIMAL(65,30),

    CONSTRAINT "purch_cr_memo_line_pkey" PRIMARY KEY ("source_db","document_no_","line_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."purchase_header" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "document_type" INTEGER NOT NULL,
    "no_" TEXT NOT NULL,
    "buy_from_vendor_no_" TEXT,
    "pay_to_vendor_no_" TEXT,
    "pay_to_name" TEXT,
    "pay_to_address" TEXT,
    "pay_to_address_2" TEXT,
    "pay_to_city" TEXT,
    "pay_to_contact" TEXT,
    "your_reference" TEXT,
    "ship_to_name" TEXT,
    "ship_to_address" TEXT,
    "ship_to_address_2" TEXT,
    "ship_to_city" TEXT,
    "ship_to_contact" TEXT,
    "order_date" TIMESTAMP(3),
    "posting_date" TIMESTAMP(3),
    "expected_receipt_date" TIMESTAMP(3),
    "posting_description" TEXT,
    "payment_terms_code" TEXT,
    "due_date" TIMESTAMP(3),
    "payment_discount" DECIMAL(65,30),
    "pmt_discount_date" TIMESTAMP(3),
    "shipment_method_code" TEXT,
    "location_code" TEXT,
    "shortcut_dimension_1_code" TEXT,
    "shortcut_dimension_2_code" TEXT,
    "vendor_posting_group" TEXT,
    "invoice_disc_code" TEXT,
    "language_code" TEXT,
    "purchaser_code" TEXT,
    "order_class" TEXT,
    "no_printed" INTEGER,
    "on_hold" TEXT,
    "applies_to_doc_type" INTEGER,
    "applies_to_doc_no_" TEXT,
    "bal_account_no_" TEXT,
    "receive" BOOLEAN,
    "invoice" BOOLEAN,
    "print_posted_documents" BOOLEAN,
    "receiving_no_" TEXT,
    "posting_no_" TEXT,
    "last_receiving_no_" TEXT,
    "last_posting_no_" TEXT,
    "vendor_order_no_" TEXT,
    "vendor_shipment_no_" TEXT,
    "vendor_invoice_no_" TEXT,
    "vendor_cr_memo_no_" TEXT,
    "vat_registration_no_" TEXT,
    "sell_to_customer_no_" TEXT,
    "gen_bus_posting_group" TEXT,
    "vat_country_region_code" TEXT,
    "buy_from_vendor_name" TEXT,
    "buy_from_address" TEXT,
    "buy_from_address_2" TEXT,
    "buy_from_city" TEXT,
    "buy_from_contact" TEXT,
    "pay_to_post_code" TEXT,
    "pay_to_county" TEXT,
    "pay_to_country_region_code" TEXT,
    "buy_from_post_code" TEXT,
    "buy_from_county" TEXT,
    "buy_from_country_region_code" TEXT,
    "ship_to_post_code" TEXT,
    "ship_to_county" TEXT,
    "ship_to_country_region_code" TEXT,
    "order_address_code" TEXT,
    "document_date" TIMESTAMP(3),
    "payment_method_code" TEXT,
    "no_series" TEXT,
    "posting_no_series" TEXT,
    "receiving_no_series" TEXT,
    "status" INTEGER,
    "invoice_discount_calculation" INTEGER,
    "invoice_discount_value" DECIMAL(65,30),
    "prepayment_no_" TEXT,
    "last_prepayment_no_" TEXT,
    "prepmt_cr_memo_no_" TEXT,
    "last_prepmt_cr_memo_no_" TEXT,
    "prepayment" DECIMAL(65,30),
    "prepayment_no_series" TEXT,
    "compress_prepayment" BOOLEAN,
    "prepayment_due_date" TIMESTAMP(3),
    "prepmt_cr_memo_no_series" TEXT,
    "prepmt_posting_description" TEXT,
    "prepmt_pmt_discount_date" TIMESTAMP(3),
    "prepmt_payment_terms_code" TEXT,
    "prepmt_payment_discount" DECIMAL(65,30),
    "incoming_document_entry_no_" INTEGER,
    "dimension_set_id" INTEGER,
    "doc_no_occurrence" INTEGER,
    "buy_from_contact_no_" TEXT,
    "pay_to_contact_no_" TEXT,
    "requested_receipt_date" TIMESTAMP(3),
    "promised_receipt_date" TIMESTAMP(3),
    "lead_time_calculation" VARCHAR(32),
    "vendor_authorization_no_" TEXT,
    "return_shipment_no_series" TEXT,
    "ship" BOOLEAN,
    "last_return_shipment_no_" TEXT,
    "id" TEXT,
    "assigned_user_id" TEXT,
    "irs_1099_code" TEXT,
    "rebate_start_date" TIMESTAMP(3),
    "rebate_end_date" TIMESTAMP(3),
    "disposition_no_" TEXT,
    "offering_no_" TEXT,
    "rebate_doc_handling" INTEGER,
    "pricing_confirm" TEXT,
    "labels_printed" BOOLEAN,
    "order_closed" BOOLEAN,
    "co_op_code" TEXT,
    "include_qty_for_pick" BOOLEAN,
    "available_date" TIMESTAMP(3),
    "manual_available_date" INTEGER,
    "priority" INTEGER,
    "drop_ship_so_no_" TEXT,
    "zone" TEXT,
    "geographic_code" TEXT,
    "allow_order_below_minimum" BOOLEAN,
    "edi_order" BOOLEAN,
    "edi_internal_doc_no_" TEXT,
    "edi_po_generated" BOOLEAN,
    "edi_po_gen_date" TIMESTAMP(3),
    "edi_released" BOOLEAN,
    "edi_ship_adv_gen" BOOLEAN,
    "edi_ship_adv_gen_date" TIMESTAMP(3),
    "edi_update_int_doc_no_" TEXT,
    "edi_trade_partner" TEXT,
    "edi_buy_from_code" TEXT,
    "e_ship_agent_code" TEXT,
    "e_ship_agent_service" TEXT,
    "world_wide_service" BOOLEAN,
    "residential_delivery" BOOLEAN,
    "cod_payment" BOOLEAN,
    "cod_cashiers_check" INTEGER,
    "shipping_payment_type" INTEGER,
    "third_party_ship_account_no_" TEXT,
    "shipping_insurance" INTEGER,
    "e_mail_confirmation_handled" INTEGER,
    "show_order" BOOLEAN,
    "freight_vendor" TEXT,
    "freight_amount" DECIMAL(65,30),
    "usda_quote_no_" TEXT,
    "usda_po_no_" TEXT,

    CONSTRAINT "purchase_header_pkey" PRIMARY KEY ("source_db","document_type","no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."gsf_item_usage" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" INTEGER NOT NULL,
    "location_code" TEXT,
    "item_no_" TEXT,
    "entry_type" INTEGER,
    "posting_date" TIMESTAMP(3),
    "month" INTEGER,
    "week" INTEGER,
    "year" INTEGER,
    "document_no_" TEXT,
    "document_type" INTEGER,
    "source_no_" TEXT,
    "source_type" INTEGER,
    "quantity" DECIMAL(65,30),
    "qty_per_unit_of_measure" DECIMAL(65,30),
    "unit_of_measure_code" TEXT,
    "redirected_from_item_no_" TEXT,
    "bill_to_customer_no_" TEXT,

    CONSTRAINT "gsf_item_usage_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateTable
CREATE TABLE "dw2_nav"."gsf_item_cost" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "location_code" TEXT NOT NULL,
    "item_no_" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "amount" DECIMAL(65,30),
    "amount_type" INTEGER,
    "calculated_amount" DECIMAL(65,30),
    "validfrom" TIMESTAMP(3),
    "validto" TIMESTAMP(3),

    CONSTRAINT "gsf_item_cost_pkey" PRIMARY KEY ("source_db","location_code","item_no_","code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."gsf_item_cost_history" (
    "source_db" TEXT,
    "hash" TEXT,
    "location_code" TEXT,
    "item_no_" TEXT,
    "code" TEXT,
    "amount" DECIMAL(65,30),
    "amount_type" INTEGER,
    "calculated_amount" DECIMAL(65,30),
    "validfrom" TIMESTAMP(3),
    "validto" TIMESTAMP(3),
    "_prisma_id" SERIAL NOT NULL,

    CONSTRAINT "gsf_item_cost_history_pkey" PRIMARY KEY ("_prisma_id")
);

-- CreateTable
CREATE TABLE "dw2_nav"."gsf_sales_price" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "bill_to_customer_no_" TEXT NOT NULL,
    "item_no_" TEXT NOT NULL,
    "unit_of_measure_code" TEXT NOT NULL,
    "unit_price" DECIMAL(65,30),
    "contract_item" BOOLEAN,
    "bid_code" TEXT,
    "last_date_updated" TIMESTAMP(3),
    "starting_date" TIMESTAMP(3),
    "ending_date" TIMESTAMP(3),

    CONSTRAINT "gsf_sales_price_pkey" PRIMARY KEY ("source_db","bill_to_customer_no_","item_no_","unit_of_measure_code")
);

-- CreateTable
CREATE TABLE "dw2_nav"."pallet_movement" (
    "source_db" TEXT NOT NULL,
    "hash" TEXT,
    "entry_no_" BIGINT NOT NULL,
    "from_bin_code" TEXT,
    "pallet_no_" TEXT,
    "line_no_" INTEGER,
    "source_no_" TEXT,
    "transaction_no_" TEXT,
    "location_code" TEXT,
    "first_scan_date" TIMESTAMP(3),
    "first_scan_time" TIMESTAMP(3),
    "last_scan_date" TIMESTAMP(3),
    "last_scan_time" TIMESTAMP(3),
    "warehouse_employee_code" TEXT,
    "completed" BOOLEAN,
    "door_no_" TEXT,
    "to_bin_code" TEXT,
    "quantity" DECIMAL(65,30),
    "type" TEXT,
    "full_pallet" BOOLEAN,
    "previous_bin_code" TEXT,
    "item_no_" TEXT,
    "cubage" DECIMAL(65,30),
    "weight" DECIMAL(65,30),

    CONSTRAINT "pallet_movement_pkey" PRIMARY KEY ("source_db","entry_no_")
);

-- CreateIndex
CREATE INDEX "item_history_source_db_no__idx" ON "dw2_nav"."item_history"("source_db", "no_");

-- CreateIndex
CREATE INDEX "item_history_validfrom_validto_idx" ON "dw2_nav"."item_history"("validfrom", "validto");
